class OvcCasePlanConstant {
  static const String casePlanEventDateSectionId = 'casePlanEventDateId';
  static const String casePlanLocatinSectionId = 'casePlanLocationId';
  static const String casePlanToGapLinkage = 'ajqTV28fydL';
  static const String casePlanGapToMonitoringLinkage = 'H7BMnqZEqGN';
  static const String casePlanGapToServiceProvisionLinkage = 'tDWIRBsuwsB';
  static const String casePlanDomainType = 'vexrPNgPBYg';
  static const String casePlanFirstGoal = 'ADc3clrQRl4';
  static const String casePlansSecondGoal = 'efNgDIqhlNs';
  static const String houseHoldCategorizationDataElement = 'aEJnSplwvsw';
  static const String householdCategorizationSection = 'house_hold_categorization';
  static const List<String> paralegalServices = [
    'AaqeRcyjbyS', // VAC Legal messaging case plan
    'QDFZ03HbjGj', // VAC Legal messaging service provision
    'x3FxC6Bw139', // VAC Legal messaging service monitoring
  ];

  static const List<String> casePlanServiceProvisionResults = [
    "y8ToqnbVz1o",
    "JnqldNamliR",
    "otd2tndsE4Z",
    "YFgrURiwirq",
    "RIpmBgYc0ZN",
    "GNQ3gDA2CTI",
    "mRoO7kgpgVg",
    "tnspdPfpuXm",
    "zK7kMYpgPQn",
    "UKczyQWCB0L",
    "KkqMjxjAR7g",
    "DoU7AeHDsUs",
    "QnFYeBNZlbf",
    "FRWCmEerPic",
    "gV77yUM8NK8",
    "qL9c5r7c6kK",
    "ESIjwQ9S6Ic",
    "gSp9bgPW52L",
    "r8wPQAog7PJ",
    "mY7GqOTKtsQ",
    "eqhzeRBMftZ",
    "lEkrLOFmLrH",
    "xTO562B5g53",
    "AnnOS2m6LZK",
    "lpTVK3t1Ahk",
    "KvLYMr8F4vg",
    "RNKOtUtLT4c",
    "rMtSykWZ4HB",
    "QDFZ03HbjGj",
    "gfKsz88uxtg",
    "ysDSdiL7wNx",
    "GImA3HB9YK5",
    "gwwUOs6yt6C",
    "aGChpBlIzcd",
    "vj0R7ySdigX",
    "JlRnllAlSk0",
    "UZJ9vqIabAY",
    "LcIB5EL3IjT",
    "hg2bpp1HqwU",
    "fvgPnlOD7e9",
    "WQlWXUmYjI2",
    "Zc0M1jsbfyA",
    "MeMaUvt3O8j"
  ];

  static const List<String> casePlanServiceProvisionReasons = [
    "dwhnvU5m667",
    "sxlVgySosg3",
    "dwhnvU5m667",
    "i9icxSZ8HCf",
    "QpE5qR1cQ6T",
    "aDOvfQ1wdIX",
    "YSsfKXdIRLG",
    "eXh6Gag1uwp",
    "g2X9vUL2d9m",
    "wZLjymsKsuj",
    "Jxlug5I3kdu",
    "Op6ws25fWWQ",
    "xdI5atw8DC4",
    "IiIVDSKX8yk",
    "JFlnkaXlXm5",
    "SODPuEmHEGV",
    "GISFLEttRtU",
    "pSkl6ibruvU",
    "itTgPQ0OrMU",
    "kBivIQr6mrW",
    "AStxMCkJhi5",
    "p77CBdxxtHI",
    "hMdC0CMKSGn",
    "xECpX8Vt1rT",
    "HGpA4kx5jLQ",
    "TN5r1EFmHWz",
    "GImA3HB9YK5",
    "OMhFxj6SYhM",
    "KWk8waoLO7N",
    "iz4CvIFovsF",
    "XUoqvbk0uVH",
    "IFggJCXLYPD",
    "aG42nUguLLW",
    "cb773khL7XB",
    "tmi1jtKYZs0",
    "ONC3bpjq525",
    "U8h0daQzXXk",
    "WVsVwfErZ7V",
    "Riyr0nniCVo",
    "yuwtSD8EyoY",
    "CxREUNzKxHB",
    "QCbFgssCzeF",
    "KppYygPZ8BL"
  ];

  static const List<String> casPlanServiceGaps = [
    "cx4xBY4jZXM",
    "XoSPWmpWXCy",
    "pbcXNnAuzfh",
    "ylSjcj6cv42",
    "d8vFkGjiux4",
    "HKCv7lkLexo",
    "BJrrrqQqwQO",
    "hJUuQ648wVF",
    "AwWKp6KmqgY",
    "JSQ3xP1NhuN",
    "x4yAqv4z2Xv",
    "AM9oJCOHM7f",
    "uvJV4WGc5ct",
    "EaJTFrklMo5",
    "DQxqyncQtwm",
    "Hvq9oisH7Gt",
    "qTf8VSoojJ2",
    "EaJTFrklMo5",
    "d2vXxEPeCq7",
    "LswSBpMoG5C",
    "dTFLFtUUeEK",
    "gCKoJgBFdob",
    "AxtahhoHcXV",
    "WrjNxZBVHCL",
    "e6NV2ZAzFEh",
    "yPP7lkomNfK",
    "kvF996ugmMl",
    "uQiyym8SEvd",
    "aPmPhwm8Zln",
    "AaqeRcyjbyS",
    "WdZ3PnW5yV6",
    "Ccp4Odlh3BE",
    "WiPTQhWLVU1",
    "PoxYSqq8Hgz",
    "hS7aONLz2cq",
    "GO3Ojp1UEX7",
    "exHDkX1gPiC",
    "yf6KmY3Rm5I",
    "X47zxNAqMv0",
    "qraZh4n14S4",
    "q2N7p3UbvSF",
    "NcMANzhhphO",
    "Cb8qzfdrg7d",
    "TdReJf2LTXA",
    "HsxFZOuV4oZ",
  ];
}
