import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

class HouseholdServiceProvision {
  static List<FormSection> getFormSections({
    required String firstDate,
  }) {
    return [
      FormSection(
          id: 'Health',
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'JnqldNamliR',
              name: 'HTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'CNnzifTDF5a',
                name: 'HTS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HTS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'sxlVgySosg3',
                name: 'HTS Comment',
                translatedName: 'Tlhaloso ea HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'YFgrURiwirq',
              name: 'HIVTREAT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVTREAT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'LtiZFxXw0Wc',
                name: 'HIVTREAT Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVTREAT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'i9icxSZ8HCf',
                name: 'HIVTREAT Comment',
                translatedName: 'Tlhaloso ea HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'eqhzeRBMftZ',
              name: 'HEALTH Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HEALTH',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'F8x8QAoFQBO',
                name: 'HEALTH Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HEALTH',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AStxMCkJhi5',
                name: 'HEALTH Comment',
                translatedName: 'Tlhaloso ea HEALTH',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'r8wPQAog7PJ',
              name: 'SAIDS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SAIDS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EgbO5h9cs5D',
                name: 'SAIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SAIDS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'itTgPQ0OrMU',
                name: 'SAIDS Comment',
                translatedName: 'Tlhaloso ea SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'gV77yUM8NK8',
              name: 'WASH MESSAGING Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea WASH MESSAGING',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'aqJBZDBzh4m',
                name: 'WASH MESSAGING Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa WASH MESSAGING',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JFlnkaXlXm5',
                name: 'WASH MESSAGING Comment',
                translatedName: 'Tlhaloso ea WASH MESSAGING',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'qL9c5r7c6kK',
              name: 'SOAKAGE PIT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SOAKAGE PIT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'pUphS6E1Gu5',
                name: 'SOAKAGE PIT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SOAKAGE PIT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SODPuEmHEGV',
                name: 'SOAKAGE PIT Comment',
                translatedName: 'Tlhaloso ea SOAKAGE PIT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'FRWCmEerPic',
              name: 'TIPPY TAP Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TIPPY TAP',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'lQYnoeqfKpe',
                name: 'TIPPY TAP Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa TIPPY TAP',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'cBCJAB8Ogxd',
              name: 'TIPPY TAP session number',
              translatedName: 'Thupelo ea TIPPY TAP',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'w4EYZpbtUV8',
                name: 'TIPPY TAP Comment',
                translatedName: 'Tlhaloso ea TIPPY TAP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'QnFYeBNZlbf',
              name: 'FOOD SUPPORT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FOOD SUPPORT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EnrZPBFxZuX',
                name: 'FOOD SUPPORT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD SUPPORT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'vXuVPQLxw1d',
              name: 'FOOD SUPPORT session number',
              translatedName: 'Thupelo ea FOOD SUPPORT',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'xdI5atw8DC4',
                name: 'FOOD SUPPORT Comment',
                translatedName: 'Tlhaloso ea FOOD SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373))
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: const Color(0xFF0000FF),
          borderColor: const Color(0xFF0000FF),
          inputFields: [
            InputField(
              id: 'xTO562B5g53',
              name: 'SILC Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SILC',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'uOMr56xoKDh',
                name: 'SILC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SILC',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SzDHpqzsiLw',
                name: 'SILC session number',
                translatedName: 'Thupelo ea SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'hMdC0CMKSGn',
                name: 'SILC Comment',
                translatedName: 'Tlhaloso ea SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'lEkrLOFmLrH',
              name: 'K/TPLOTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea K/TPLOTS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'F8ALMOcc6C1',
                name: 'K/TPLOTS Service Provision Date',
                // translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa K/TPLOTS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'p77CBdxxtHI',
                name: 'K/TPLOTS Comment',
                translatedName: 'Tlhaloso ea K/TPLOTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Safe',
          name: 'DOMAIN SAFE',
          translatedName: 'TSIRELETSO',
          color: const Color(0xFF0F9587),
          borderColor: const Color(0xFF0F9587),
          inputFields: [
            InputField(
              id: 'gfKsz88uxtg',
              name: 'LEGAL PROTECTION Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea LEGAL PROTECTION',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'P06od0qmlSR',
                name: 'LEGAL PROTECTION Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa LEGAL PROTECTION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'NwtohlveKHW',
                name: 'LEGAL PROTECTION session number',
                translatedName: 'Thupelo ea LEGAL PROTECTION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iz4CvIFovsF',
                name: 'LEGAL PROTECTION Comment',
                translatedName: 'Tlhaloso ea LEGAL PROTECTION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'aGChpBlIzcd',
              name: 'BIRTHCERT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea BIRTHCERT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'AXLxNo9pz8c',
                name: 'BIRTHCERT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa BIRTHCERT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'RTEBrgDTe02',
                name: 'BIRTHCERT session number',
                translatedName: 'Thupelo ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cb773khL7XB',
                name: 'BIRTHCERT Comment',
                translatedName: 'Tlhaloso ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          name: 'Other Activities',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'TSx4O9Tf5v2',
              name: 'OTHER ACTIVITIES Service provided',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'x5VlMVD2a4E',
                name: 'OTHER ACTIVITIES Service Provision Date',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'mPMxntJR5Qy',
                name: 'OTHER ACTIVITIES session number',
                translatedName: 'Thupelo ea OTHER ACTIVITIES',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rJaHpLnWvfg',
                name: 'OTHER ACTIVITIES Comment',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          ])
    ];
  }
}
