import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

class HouseholdServiceProvision {
  static List<FormSection> getFormSections({
    required String firstDate,
  }) {
    return [
      FormSection(
          id: 'Health',
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'y8ToqnbVz1o',
              name: 'HIVS&D Service provided',
              translatedName: "Lits'ebeletso tsa HIVS&D li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'GyG2HcLsVka',
                name: 'HIVS&D Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVS&D',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'uU4TvD2O1uL',
              name: 'HIVS&D session number',
              translatedName: 'Thupelo ea HIVS&D',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'dwhnvU5m667',
                name: 'HIVS&D Comment',
                translatedName: 'Tlhaloso ea HIVS&D',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'JnqldNamliR',
              name: 'HTS Service provided',
              valueType: 'TRUE_ONLY',
              translatedName: 'Litsebeletso tsa HTS li fanoe',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'CNnzifTDF5a',
                name: 'HTS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HTS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'sxlVgySosg3',
                name: 'HTS Comment',
                translatedName: 'Tlhaloso ea HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'otd2tndsE4Z',
              name: 'HIV ADHERANCE SUPPORT Service provided',
              translatedName:
                  "Lits'ebeletso tsa HIV ADHERANCE SUPPORT li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'ruZFn94Hcyw',
                name: 'HIV ADHERANCE SUPPORT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa HIV ADHERANCE SUPPORT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dwhnvU5m667',
                name: 'HIV ADHERANCE SUPPORT Comment',
                translatedName: 'Tlhaloso ea HIV ADHERANCE SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'YFgrURiwirq',
              name: 'HIVTREAT Service provided',
              valueType: 'TRUE_ONLY',
              translatedName: 'Litsebeletso tsa HIVTREAT li fanoe',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'LtiZFxXw0Wc',
                name: 'HIVTREAT Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVTREAT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'i9icxSZ8HCf',
                name: 'HIVTREAT Comment',
                translatedName: 'Tlhaloso ea HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'ESIjwQ9S6Ic',
              name: 'PRG&L Service provided',
              translatedName: "Lits'ebeletso tsa PRG&L li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EYv3aMwJOUN',
                name: 'PRG&L Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PRG&L',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GISFLEttRtU',
                name: 'PRG&L Comment',
                translatedName: 'Tlhaloso ea PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'r8wPQAog7PJ',
              name: 'SAIDS Service provided',
              translatedName: "Lits'ebeletso tsa SAIDS li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EgbO5h9cs5D',
                name: 'SAIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SAIDS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'itTgPQ0OrMU',
                name: 'SAIDS Comment',
                translatedName: 'Tlhaloso ea SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'QnFYeBNZlbf',
              name: 'FOOD SUPPORT Service provided',
              translatedName: "Lits'ebeletso tsa FOOD SUPPORT li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EnrZPBFxZuX',
                name: 'FOOD SUPPORT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD SUPPORT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'vXuVPQLxw1d',
              name: 'FOOD SUPPORT session number',
              translatedName: 'Thupelo ea FOOD SUPPORT',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'xdI5atw8DC4',
                name: 'FOOD SUPPORT Comment',
                translatedName: 'Tlhaloso ea FOOD SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'tnspdPfpuXm',
              name: 'FOOD PREV  Service provided',
              translatedName: "Lits'ebeletso tsa FOOD PREV li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'V1HnY5m2Pmv',
                name: 'FOOD PREV Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD PREV',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'YRUnLuPerwn',
              name: 'FOOD PREV  session number',
              translatedName: 'Thupelo ea FOOD PREV ',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'eXh6Gag1uwp',
                name: 'FOOD PREV  Comment',
                translatedName: 'Tlhaloso ea FOOD PREV ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'zK7kMYpgPQn',
              name: 'FOOD PREP  Service provided',
              translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa FOOD PREP',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'GtejBpkVvtD',
                name: 'FOOD PREP Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD PREP',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'F6z3SQxLskG',
              name: 'FOOD PREP session number',
              translatedName: 'Thupelo ea FOOD PREP ',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'g2X9vUL2d9m',
                name: 'FOOD PREP Comment',
                translatedName: 'Tlhaloso ea FOOD PREP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'gV77yUM8NK8',
              name: 'WASH MESSAGING Service provided',
              translatedName: "Lits'ebeletso tsa WASH MESSAGING li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'aqJBZDBzh4m',
                name: 'WASH MESSAGING Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa WASH MESSAGING',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JFlnkaXlXm5',
                name: 'WASH MESSAGING Comment',
                translatedName: 'Tlhaloso ea WASH MESSAGING',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'qL9c5r7c6kK',
              name: 'SOAKAGE PIT Service provided',
              translatedName: "Lits'ebeletso tsa SOAKAGE PIT li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'pUphS6E1Gu5',
                name: 'SOAKAGE PIT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SOAKAGE PIT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SODPuEmHEGV',
                name: 'SOAKAGE PIT Comment',
                translatedName: 'Tlhaloso ea SOAKAGE PIT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'FRWCmEerPic',
              name: 'TIPPY TAP Service provided',
              translatedName: "Lits'ebeletso tsa TIPPY TAP li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'lQYnoeqfKpe',
                name: 'TIPPY TAP Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa TIPPY TAP',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'cBCJAB8Ogxd',
              name: 'TIPPY TAP session number',
              translatedName: 'Thupelo ea TIPPY TAP',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'w4EYZpbtUV8',
                name: 'TIPPY TAP Comment',
                translatedName: 'Tlhaloso ea TIPPY TAP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'eqhzeRBMftZ',
              name: 'ANY HEALTH RELATED Service provided',
              translatedName: 'Litsebeletso tsa ANY HEALTH RELATED tse fanoe',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'F8x8QAoFQBO',
                name: 'ANY HEALTH RELATED Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa ANY HEALTH RELATED',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AStxMCkJhi5',
                name: 'ANY HEALTH RELATED Comment',
                translatedName: 'Tlhaloso ea ANY HEALTH RELATED',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: const Color(0xFF0000FF),
          borderColor: const Color(0xFF0000FF),
          inputFields: [
            InputField(
              id: 'xTO562B5g53',
              name: 'SILC Service provided',
              translatedName: "Lits'ebeletso tsa SILC li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'uOMr56xoKDh',
                name: 'SILC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SILC',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SzDHpqzsiLw',
                name: 'SILC session number',
                translatedName: 'Thupelo ea SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'hMdC0CMKSGn',
                name: 'SILC Comment',
                translatedName: 'Tlhaloso ea SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'lEkrLOFmLrH',
              name: 'K/TPLOTS Service provided',
              translatedName: "Lits'ebeletso tsa K/TPLOTS li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'F8ALMOcc6C1',
                name: 'K/TPLOTS Service Provision Date',
                translatedName: "Lits'ebeletso tsa K/TPLOTS li fanoe",
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'p77CBdxxtHI',
                name: 'K/TPLOTS Comment',
                translatedName: 'Tlhaloso ea K/TPLOTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'lpTVK3t1Ahk',
              name: 'FINANCIAL EDUCATION  Service provided',
              translatedName: "Lits'ebeletso tsa FINANCIAL EDUCATION li fanoe",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'j1yzHzO0w6w',
                name: 'FINANCIAL EDUCATION  Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FINANCIAL EDUCATION ',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'KvHf0rBfa1L',
                name: 'FINANCIAL EDUCATION  session number',
                translatedName: 'Thupelo ea FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HGpA4kx5jLQ',
                name: 'FINANCIAL EDUCATION  Comment',
                translatedName: 'Tlhaloso ea FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
        id: 'Safe',
        name: 'DOMAIN SAFE',
        translatedName: 'TSIRELETSO',
        color: const Color(0xFF0F9587),
        borderColor: const Color(0xFF0F9587),
        inputFields: [
          InputField(
            id: 'gfKsz88uxtg',
            name: 'LEGAL PROTECTION Service provided',
            translatedName: "Lits'ebeletso tsa LEGAL PROTECTION li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'P06od0qmlSR',
              name: 'LEGAL PROTECTION Service Provision Date',
              translatedName:
                  'Letsatsi la Kabo ea Litšebeletso tsa LEGAL PROTECTION',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'NwtohlveKHW',
              name: 'LEGAL PROTECTION session number',
              translatedName: 'Thupelo ea LEGAL PROTECTION',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'iz4CvIFovsF',
              name: 'LEGAL PROTECTION Comment',
              translatedName: 'Tlhaloso ea LEGAL PROTECTION',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'aGChpBlIzcd',
            name: 'BIRTHCERT Service provided',
            translatedName: "Lits'ebeletso tsa BIRTHCERT li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'AXLxNo9pz8c',
              name: 'BIRTHCERT Service Provision Date',
              translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa BIRTHCERT',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'RTEBrgDTe02',
              name: 'BIRTHCERT session number',
              translatedName: 'Thupelo ea BIRTHCERT',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'cb773khL7XB',
              name: 'BIRTHCERT Comment',
              translatedName: 'Tlhaloso ea BIRTHCERT',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'rMtSykWZ4HB',
            name: 'VAC MESSAGING Service provided',
            translatedName: "Lits'ebeletso tsa moalaetsa oa VAC li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'qwnfgBG2web',
              name: 'VAC MESSAGING Service Provision Date',
              translatedName:
                  'Letsatsi la Kabo ea Litšebeletso tsa VAC MESSAGING',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'YPImSLRMLWH',
              name: 'VAC MESSAGING session number',
              translatedName: "Lits'ebeletso tsa molaetsa oa session number",
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'OMhFxj6SYhM',
              name: 'VAC MESSAGING Comment',
              translatedName: 'Tlhaloso ea VAC MESSAGING',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'QDFZ03HbjGj',
            name: 'VAC Legal Messaging Service provided',
            translatedName: "Litsebeletso tsa molaetsa oa molao li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'Dw1xLXILErU',
              name: 'VAC Legal Messaging Provision Date',
              translatedName:
                  'Letsatsi la Kabo ea Litšebeletso tsa VAC Legal Messaging',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'P4PMMDgWCSA',
              name: 'VAC Legal Messaging session number',
              translatedName: 'Thupelo ea VAC Legal Messaging',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'KWk8waoLO7N',
              name: 'VAC Legal Messaging Comment',
              translatedName: 'Tlhaloso ea VAC Legal Messaging',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'ysDSdiL7wNx',
            name: 'COUNSELLING Service provided',
            translatedName: "Litsebeletso tsa boeletsi bp fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'pBVmFpsSGN7',
              name: 'COUNSELLING Service Provision Date',
              translatedName:
                  'Letsatsi la Kabo ea Litšebeletso tsa COUNSELLING',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'LkQxvdt6YCw',
              name: 'COUNSELLING session number',
              translatedName: 'Thupelo ea COUNSELLING',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'XUoqvbk0uVH',
              name: 'COUNSEL Comment',
              translatedName: 'Tlhaloso ea COUNSELLING',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'GImA3HB9YK5',
            name: 'RTEEN/Parenting  Service provided',
            translatedName: "Lits'ebeletso tsa RTEEN/Parenting  li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'fFuabYbLUjz',
              name: 'RTEEN/Parenting Service Provision Date',
              translatedName:
                  'Letsatsi la Kabo ea Litšebeletso tsa RTEEN/Parenting',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'QBNhlIan0LR',
              name: 'RTEEN/Parenting session number',
              translatedName: 'Thupelo ea RTEEN',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'IFggJCXLYPD',
              name: 'RTEEN/Parenting Comment',
              translatedName: 'Tlhaloso ea RTEEN/Parenting',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'gwwUOs6yt6C',
            name: 'P&FC Service provided',
            translatedName: "Lits'ebeletso tsa P&FC li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'w2HlBCfHbZR',
              name: 'P&FC Service Provision Date',
              translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa P&FC',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'n30r7v0ti1s',
              name: 'P&FC session number',
              translatedName: 'Thupelo ea P&FC',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'aG42nUguLLW',
              name: 'P&FC Comment',
              translatedName: 'Tlhaloso ea P&FC',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
            id: 'JlRnllAlSk0',
            name: 'SHELTER Service provided',
            translatedName: "Lits'ebeletso tsa SHELTER li fanoe",
            valueType: 'TRUE_ONLY',
            inputColor: const Color(0xFF0F9587),
            labelColor: const Color(0xFF737373),
          ),
          InputField(
              id: 'VlOw6vrLsp5',
              name: 'SHELTER Service Provision Date',
              translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SHELTER',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'ONC3bpjq525',
              name: 'SHELTER Comment',
              translatedName: 'Tlhaloso ea SHELTER',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
        ],
      ),
    ];
  }
}
