import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

//@TODO add referrences for service's session numbers
class HouseholdServiceProvision {
  static List<FormSection> getFormSections() {
    return [
      FormSection(
          id: 'Health',
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          color: Color(0xFF4D9E49),
          borderColor: Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'JnqldNamliR',
              name: 'HTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'CNnzifTDF5a',
                name: 'HTS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HTS',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'UQKbbPTRaB8',
              name: 'HTS session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'sxlVgySosg3',
                name: 'HTS Comment',
                translatedName: 'Tlhaloso ea HTS',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'YFgrURiwirq',
              name: 'HIVTREAT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVTREAT',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'LtiZFxXw0Wc',
                name: 'HIVTREAT Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVTREAT',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'BOuCiVoZ7sT',
              name: 'HIVTREAT session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'i9icxSZ8HCf',
                name: 'HIVTREAT Comment',
                translatedName: 'Tlhaloso ea HIVTREAT',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'HzI5X2yHef6',
              name: 'HIVS&D Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVS&D',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'GyG2HcLsVka',
                name: 'HIVS&D Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVS&D',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'uU4TvD2O1uL',
              name: 'HIVS&D session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'y8ToqnbVz1o',
                name: 'HIVS&D Comment',
                translatedName: 'Tlhaloso ea HIVS&D',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'eqhzeRBMftZ',
              name: 'HEALTH Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HEALTH',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'F8x8QAoFQBO',
                name: 'HEALTH Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HEALTH',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'ze0vffQrd1R',
              name: 'HEALTH session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HEALTH',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'AStxMCkJhi5',
                name: 'HEALTH Comment',
                translatedName: 'Tlhaloso ea HEALTH',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'ESIjwQ9S6Ic',
              name: 'PRG&L Service provided',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'EYv3aMwJOUN',
                name: 'PRG&L Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PRG&L',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'jR2yBxtyPRa',
              name: 'PRG&L session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PRG&L',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'GISFLEttRtU',
                name: 'PRG&L Comment',
                translatedName: 'Tlhaloso ea PRG&L',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'r8wPQAog7PJ',
              name: 'SAIDS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SAIDS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'EgbO5h9cs5D',
                name: 'SAIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SAIDS',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'zzH8cEeSDFz',
              name: 'SAIDS session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SAIDS',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'itTgPQ0OrMU',
                name: 'SAIDS Comment',
                translatedName: 'Tlhaloso ea SAIDS',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'gV77yUM8NK8',
              name: 'WASHMES Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea WASHMES',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'aqJBZDBzh4m',
                name: 'WASHMES Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa WASHMES',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'EtENRPlSnO0',
              name: 'WASHMES session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea WASHMES',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'JFlnkaXlXm5',
                name: 'WASHMES Comment',
                translatedName: 'Tlhaloso ea WASHMES',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'qL9c5r7c6kK',
              name: 'SOACKAGE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SOACKAGE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'pUphS6E1Gu5',
                name: 'SOACKAGE Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SOACKAGE',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'k5RGRpWRbbs',
              name: 'SOACKAGE session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SOACKAGE',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'SODPuEmHEGV',
                name: 'SOACKAGE Comment',
                translatedName: 'Tlhaloso ea SOACKAGE',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'FRWCmEerPic',
              name: 'TIPPY Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TIPPY',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'lQYnoeqfKpe',
                name: 'TIPPY Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa TIPPY',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'cBCJAB8Ogxd',
              name: 'TIPPY session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TIPPY',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'w4EYZpbtUV8',
                name: 'TIPPY Comment',
                translatedName: 'Tlhaloso ea TIPPY',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373))
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: Color(0xFF0000FF),
          borderColor: Color(0xFF0000FF),
          inputFields: [
            InputField(
              id: 'xTO562B5g53',
              name: 'SILC Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SILC',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'uOMr56xoKDh',
                name: 'SILC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SILC',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'SzDHpqzsiLw',
                name: 'SILC session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea SILC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'hMdC0CMKSGn',
                name: 'SILC Comment',
                translatedName: 'Tlhaloso ea SILC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'lpTVK3t1Ahk',
              name: 'FE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'j1yzHzO0w6w',
                name: 'FE Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa FE',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'KvHf0rBfa1L',
                name: 'FE session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea FE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'QnfPxpJvb1D',
                name: 'FE Comment',
                translatedName: 'Tlhaloso ea FE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'kcoDiGNXWpA',
              name: 'EST COOPRTVS Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea EST COOPRTVS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'qwmtkJDotBk',
                name: 'EST COOPRTVS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa EST COOPRTVS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'Z6VwHVRIh48',
                name: 'EST COOPRTVS session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea EST COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'giA7cceTW8w',
                name: 'EST COOPRTVS Comment',
                translatedName: 'Tlhaloso ea EST COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'fgDPoYtifQI',
              name: 'FUNCT COOPRTVS Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea FUNCT COOPRTVS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'lbCCs00yuGQ',
                name: 'FUNCT COOPRTVS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FUNCT COOPRTVS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'kehmVw8hmos',
                name: 'FUNCT COOPRTVS session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea FUNCT COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'TNmg7uRUWgC',
                name: 'FUNCT COOPRTVS Comment',
                translatedName: 'Tlhaloso ea FUNCT COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'cbqS6IoSbwI',
              name: 'MARKT COOPRTVS Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea MARKT COOPRTVS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'zKkaaSt1c8V',
                name: 'MARKT COOPRTVS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa MARKT COOPRTVS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'iwuAHCCxe5m',
                name: 'MARKT COOPRTVS session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea MARKT COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'KpUgwivl5Cr',
                name: 'MARKT COOPRTVS Comment',
                translatedName: 'Tlhaloso ea MARKT COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'lEkrLOFmLrH',
              name: 'K/TPLOTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea K/TPLOTS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'F8ALMOcc6C1',
                name: 'K/TPLOTS Service Provision Date',
                // translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa K/TPLOTS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'ereN7hP7yuT',
                name: 'K/TPLOTS session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea K/TPLOTS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'p77CBdxxtHI',
                name: 'K/TPLOTS Comment',
                translatedName: 'Tlhaloso ea K/TPLOTS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Safe',
          name: 'DOMAIN SAFE',
          translatedName: 'TSIRELETSO',
          color: Color(0xFF0F9587),
          borderColor: Color(0xFF0F9587),
          inputFields: [
            InputField(
              id: 'gwwUOs6yt6C',
              name: 'P&FC Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea P&FC',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'w2HlBCfHbZR',
                name: 'P&FC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa P&FC',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'n30r7v0ti1s',
                name: 'P&FC session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea P&FC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'aG42nUguLLW',
                name: 'P&FC Comment',
                translatedName: 'Tlhaloso ea P&FC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'rMtSykWZ4HB',
              name: 'VAC Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'qwnfgBG2web',
                name: 'VAC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa VAC',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'YPImSLRMLWH',
                name: 'VAC session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'OMhFxj6SYhM',
                name: 'VAC Comment',
                translatedName: 'Tlhaloso ea VAC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'QDFZ03HbjGj',
              name: 'VAC Legal Messaging Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea VAC Legal Messaging',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'Dw1xLXILErU',
                name: 'VAC Legal Messaging Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa VAC Legal Messaging',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'P4PMMDgWCSA',
                name: 'VAC Legal Messaging session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea P&FC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'KWk8waoLO7N',
                name: 'VAC Legal Messaging Comment',
                translatedName: 'Tlhaloso ea VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'cuy4Ai7mBbA',
              name: 'SURVIVORS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SURVIVORS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'C5bhgqcq6Qn',
                name: 'SURVIVORS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SURVIVORS',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'sONWFapy6yk',
                name: 'SURVIVORS session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea SURVIVORS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'h10Iktl4KKR',
                name: 'SURVIVORS Comment',
                translatedName: 'Tlhaloso ea SURVIVORS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'ysDSdiL7wNx',
              name: 'COUNSEL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea COUNSEL',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'pBVmFpsSGN7',
                name: 'COUNSEL Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa COUNSEL',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'LkQxvdt6YCw',
                name: 'COUNSEL session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea COUNSEL',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'XUoqvbk0uVH',
                name: 'COUNSEL Comment',
                translatedName: 'Tlhaloso ea COUNSEL',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'UZJ9vqIabAY',
              name: 'ABUSE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea ABUSE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'pGDK3Y7tN2B',
                name: 'ABUSE Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa ABUSE',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'Gs4XVviJB3r',
                name: 'ABUSE session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea ABUSE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'U8h0daQzXXk',
                name: 'ABUSE Comment',
                translatedName: 'Tlhaloso ea ABUSE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'gfKsz88uxtg',
              name: 'LEGALPROT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea LEGALPROT',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'P06od0qmlSR',
                name: 'LEGALPROT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa LEGALPROT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'NwtohlveKHW',
                name: 'LEGALPROT session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea LEGALPROT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'iz4CvIFovsF',
                name: 'LEGALPROT Comment',
                translatedName: 'Tlhaloso ea LEGALPROT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'aGChpBlIzcd',
              name: 'BIRTHCERT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea BIRTHCERT',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'AXLxNo9pz8c',
                name: 'BIRTHCERT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa BIRTHCERT',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'RTEBrgDTe02',
                name: 'BIRTHCERT session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'cb773khL7XB',
                name: 'BIRTHCERT Comment',
                translatedName: 'Tlhaloso ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Schooled',
          name: 'DOMAIN SCHOOLED',
          translatedName: 'TSA SEKOLO',
          color: Color(0xFF9B2BAE),
          borderColor: Color(0xFF9B2BAE),
          inputFields: [
            InputField(
              id: 'EYhFIkTpUS3',
              name: 'PTS4G Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4G',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'rM13n9K4vE7',
                name: 'PTS4G Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PTS4G',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'uVd1sxrd6C7',
                name: 'PTS4G session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4G',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'VlReEXXH1WN',
                name: 'PTS4G Comment',
                translatedName: 'Tlhaloso ea PTS4G',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'IiKUlAeSIE3',
              name: 'PTS4NG Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4NG',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'rUCb6Afcz9U',
                name: 'PTS4NG Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PTS4NG',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'p8Ha7w4plCe',
                name: 'PTS4NG session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4NG',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'sD0zbIksKTY',
                name: 'PTS4NG Comment',
                translatedName: 'Tlhaloso ea PTS4NG',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'hg2bpp1HqwU',
              name: 'HWCLUB Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HWCLUB',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'wB2jXLTYtDb',
                name: 'HWCLUB Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HWCLUB',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'cuLeuQsq7ZG',
                name: 'HWCLUB session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea HWCLUB',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'Riyr0nniCVo',
                name: 'HWCLUB Comment',
                translatedName: 'Tlhaloso ea HWCLUB',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
          ]),
      FormSection(
          name: 'Other Activities',
          color: Color(0xFF4D9E49),
          borderColor: Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'TSx4O9Tf5v2',
              name: 'OTHER ACTIVITIES Service provided',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'x5VlMVD2a4E',
                name: 'OTHER ACTIVITIES Service Provision Date',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'mPMxntJR5Qy',
                name: 'OTHER ACTIVITIES session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea OTHER ACTIVITIES',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'rJaHpLnWvfg',
                name: 'OTHER ACTIVITIES Comment',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
          ])
    ];
  }
}
