import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

class OvcHouseholdServicesCasePlanGaps {
  static List<FormSection> getFormSections({
    required String firstDate,
  }) {
    return [
      FormSection(
          id: 'Health',
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
                id: 'cx4xBY4jZXM',
                name: 'HIV S&D',
                translatedName: 'Tšebeletso ea HIV S&D',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'b6hvMQuH3oJ',
                name: '(HIV S&D) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIV S&D',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iy0KZ7K4qld',
                name: '(HIV S&D) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIV S&D',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SIEeRmPm0Q0',
                allowFuturePeriod: true,
                name: '(HIV S&D) Projected date for completion',
                translatedName: 'Letsatsi la HIV S&D le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XoSPWmpWXCy',
                translatedName: 'Tšebeletso ea  HTS',
                name: 'HTS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vqf67Edjw4y',
                name: '(HTS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bQtXR6iQyo8',
                name: '(HTS) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iFv7FJeG3V1',
                allowFuturePeriod: true,
                translatedName: 'Letsatsi la HTS le tla phetheloa',
                name: '(HTS) Projected date for completion',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HKCv7lkLexo',
                name: 'HIV ADHERANCE SUPPORT',
                translatedName: 'Tšebeletso ea HIV ADHERANCE SUPPORT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd3X7sRgkQkl',
                name: '(HIV ADHERANCE SUPPORT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIV ADHERANCE SUPPORT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd8vFkGjiux4',
                name: '(HIV ADHERANCE SUPPORT ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIV ADHERANCE SUPPORT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JzlLk2tW4xh',
                allowFuturePeriod: true,
                name: '( HIV ADHERANCE SUPPORT ) Projected date for completion',
                translatedName: 'Letsatsi la HIV ADHERANCE SUPPORT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ylSjcj6cv42',
                name: 'HIVTREAT',
                translatedName: 'Tšebeletso ea  HIVTREAT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'elqeNdaYNTS',
                name: '(HIVTREAT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'IhzyIy3tzo0',
                name: '(HIVTREAT) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qMrZcC7VvCV',
                allowFuturePeriod: true,
                name: '(HIVTREAT) Projected date for completion',
                translatedName: 'Letsatsi la HIVTREAT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dTFLFtUUeEK',
                name: 'SAIDS',
                translatedName: 'Tšebeletso ea  SAIDS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'emAJOTWYHVq',
                name: '(SAIDS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'lwa1qFrFISz',
                name: '(SAIDS) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jlu7TDN7khJ',
                allowFuturePeriod: true,
                name: '(SAIDS) Projected date for completion',
                translatedName: 'Letsatsi la SAIDS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EaJTFrklMo5',
                name: 'FOOD SUPPORT',
                translatedName: 'Tšebeletso ea  FOOD SUPPORT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rHgxOKM91wi',
                name: '(FOOD SUPPORT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'v00dsDvhCRu',
                name: '(FOOD SUPPORT) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WAq2HJHXZYS',
                allowFuturePeriod: true,
                name: '(FOOD SUPPORT) Projected date for completion',
                translatedName: 'Letsatsi la FOOD SUPPORT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AwWKp6KmqgY',
                name: 'FOOD PREV ',
                translatedName: 'Tšebeletso ea FOOD PREV ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cXCdR7BvrSM',
                name: '(FOOD PREV ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD PREV ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'u8yn7sY5eOX',
                name: '(FOOD PREV ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD PREV ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Mu0LxlAOoSp',
                allowFuturePeriod: true,
                name: '(FOOD PREV ) Projected date for completion',
                translatedName: 'Letsatsi la FOOD PREV  le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JSQ3xP1NhuN',
                name: 'FOOD PREP ',
                translatedName: 'Tšebeletso ea FOOD PREP',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'k6jzyzGOu5Y',
                name: '(FOOD PREP ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD PREP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HrCyUkuZath',
                name: '(FOOD PREP ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD PREP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MdmCqSwcrlk',
                allowFuturePeriod: true,
                name: '(FOOD PREP ) Projected date for completion',
                translatedName: 'Letsatsi la FOOD PREP le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Hvq9oisH7Gt',
                name: 'WASH MESSAGING',
                translatedName: 'Tšebeletso ea  WASH MESSAGING',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ue6xLPEURqt',
                name: '(WASH MESSAGING) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho WASH MESSAGING',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vIbKIUgzBU4',
                name: '(WASH MESSAGING) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho WASH MESSAGING',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'tQ3pKyJ0X9d',
                allowFuturePeriod: true,
                name: '(WASH MESSAGING) Projected date for completion',
                translatedName: 'Letsatsi la WASH MESSAGING le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qTf8VSoojJ2',
                name: 'SOACKAGE PIT',
                translatedName: 'Tšebeletso ea  SOACKAGE PIT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ontonbgTJ8k',
                name: '(SOACKAGE PIT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SOACKAGE PIT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AjYKLfIQPtT',
                name: '(SOACKAGE PIT) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SOACKAGE PIT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'M2Aqvn027cd',
                allowFuturePeriod: true,
                name: '(SOACKAGE PIT) Projected date for completion',
                translatedName: 'Letsatsi la SOACKAGE PIT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'DQxqyncQtwm',
                name: 'TIPPY TAP',
                valueType: 'TRUE_ONLY',
                translatedName: 'Tšebeletso ea  TIPPY TAP',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'P4I6rK6Xqxw',
                name: '(TIPPY TAP) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho TIPPY TAP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WFKe1YpH1uK',
                name: '(TIPPY TAP) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho TIPPY TAP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'YJXb5rSVP0L',
                allowFuturePeriod: true,
                name: '(TIPPY TAP) Projected date for completion',
                translatedName: 'Letsatsi la TIPPY TAP le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd2vXxEPeCq7',
                name: 'PRG&L',
                translatedName: 'Tšebeletso a PRG&L',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GnsYKEE2fnr',
                name: '(PRG&L) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'X2CA3iQZU74',
                name: '(PRG&L) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kpzlTeM0673',
                allowFuturePeriod: true,
                name: '(PRG&L) Projected date for completion',
                translatedName: 'Letsatsi la PRG&L le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AxtahhoHcXV',
                name: 'ANY HEALTH RELATED',
                translatedName: 'Tšebeletso ea  ANY HEALTH RELATED',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'G6GkSeccLmB',
                name: '(ANY HEALTH RELATED) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho ANY HEALTH RELATED',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GULhHDCXRvz',
                name: '(ANY HEALTH RELATED) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho ANY HEALTH RELATED',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ugZKkd3UMNF',
                allowFuturePeriod: true,
                name: '(ANY HEALTH RELATED) Projected date for completion',
                translatedName: 'Letsatsi la ANY HEALTH RELATED le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: const Color(0xFF0000FF),
          borderColor: const Color(0xFF0000FF),
          inputFields: [
            InputField(
                id: 'e6NV2ZAzFEh',
                name: 'SILC',
                valueType: 'TRUE_ONLY',
                translatedName: 'Tšebeletso ea  SILC',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JtfKB58MvNK',
                name: '(SILC) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MMjndp2xsoQ',
                name: '(SILC) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Hdf3EtTGfAb',
                allowFuturePeriod: true,
                name: '(SILC) Projected date for completion',
                translatedName: 'Letsatsi la SILC le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WrjNxZBVHCL',
                name: 'K/TPLOTS',
                valueType: 'TRUE_ONLY',
                translatedName: 'Tšebeletso ea  K/TPLOTS',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'NWBZilCPutW',
                name: '(K/TPLOTS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho K/TPLOTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'boUUP8UeWDL',
                name: '(K/TPLOTS) Name of responsible external person',
                translatedName: 'Motho ea ikarabellang ka ntle ho K/TPLOTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd3k97F0fS2y',
                allowFuturePeriod: true,
                name: '(K/TPLOTS) Projected date for completion',
                translatedName: 'Letsatsi la K/TPLOTS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kvF996ugmMl',
                name: 'FINANCIAL EDUCATION ',
                translatedName: 'Tšebeletso ea FINANCIAL EDUCATION ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OMtcDA7tcVL',
                name: '(FINANCIAL EDUCATION ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Mz24UpWclb3',
                name: '(FINANCIAL EDUCATION ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'zVCkEJuy2t8',
                allowFuturePeriod: true,
                name: '(FINANCIAL EDUCATION ) Projected date for completion',
                translatedName: 'Letsatsi la FINANCIAL EDUCATION le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
        id: 'Safe',
        name: 'DOMAIN SAFE',
        translatedName: 'TSIRELETSO',
        color: const Color(0xFF0F9587),
        borderColor: const Color(0xFF0F9587),
        inputFields: [
          InputField(
              id: 'WdZ3PnW5yV6',
              name: 'LEGAL PROTECTION',
              translatedName: "TS'IRELETSO EA MOLAO",
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'dJR6GJyHCTr',
              name: '(LEGAL PROTECTION) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho  LEGAL PROTECTION',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'cu1UkUUTbME',
              name: '(LEGAL PROTECTION) Name of responsible external person',
              translatedName: 'Motho ea ikarabellang ka ntle ho  LEGAL PROTECTION',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'OIw6D3I6BmY',
              allowFuturePeriod: true,
              name: '(LEGAL PROTECTION) Projected date for completion',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'hS7aONLz2cq',
              name: 'BIRTHCERT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'LDH3TLjHUYK',
              name: '(BIRTHCERT) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho BIRTHCERT',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'Pd5CyDu2Z54',
              name: '(BIRTHCERT) Name of responsible external person',
              translatedName: 'Motho ea ikarabellang ka ntle ho BIRTHCERT',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'SvkvfRNqyh2',
              allowFuturePeriod: true,
              name: '(BIRTHCERT) Projected date for completion',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'aPmPhwm8Zln',
              name: 'VAC/VAC Messaging',
              translatedName: 'Tšebeletso a VAC/VAC Messaging',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'jKqWohAPqyW',
              name: '(VAC/VAC Messaging) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho VAC/VAC Messaging',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'U8jnyQsnfBD',
              name: '(VAC/VAC Messaging) Name of responsible external Person',
              translatedName: 'Motho ea ikarabellang ka ntle ho VAC/VAC Messaging',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'wGrQeSydiwd',
              allowFuturePeriod: true,
              name: '(VAC/VAC Messaging) Projected date for completion',
              translatedName: 'Letsatsi la VAC/VAC Messaging le tla phetheloa',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'AaqeRcyjbyS',
              name: 'VAC Legal Messaging',
              translatedName: 'Tšebeletso a VAC Legal Messaging',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'TizNGPP6e1d',
              name: '(VAC Legal Messaging) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho VAC Legal Messaging',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'Q7GxvZD6h99',
              name: '(VAC Legal Messaging) Name of responsible external Person',
              translatedName: 'Motho ea ikarabellang ka ntle ho VAC Legal Messaging',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'A4xYu8BYOg7',
              allowFuturePeriod: true,
              name: '(VAC Legal Messaging) Projected date for completion',
              translatedName: 'Letsatsi la VAC Legal Messaging le tla phetheloa',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'Ccp4Odlh3BE',
              name: 'COUNSELLING',
              translatedName: 'Tšebeletso a COUNSELLING',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'kGoKVtkQxvk',
              name: '(COUNSELLING) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho COUNSELLING',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'yoI0bu18mPo',
              name: '(COUNSELLING) Name of responsible external Person',
              translatedName: 'Motho ea ikarabellang ka ntle ho COUNSELLING',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'Io9nnYXCvWR',
              allowFuturePeriod: true,
              name: '(COUNSELLING) Projected date for completion',
              translatedName: 'Letsatsi la COUNSELLING le tla phetheloa',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'WiPTQhWLVU1',
              name: 'RTEEN/Parenting',
              translatedName: 'Tšebeletso a RTEEN/Parenting',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'E2CWztOcx2X',
              name: '(RTEEN/Parenting) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho RTEEN',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'xFXc0oacTEb',
              name: '(RTEEN/Parenting) Name of responsible external Person',
              translatedName: 'Motho ea ikarabellang ka ntle ho RTEEN',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'BpLk6ruSL7e',
              allowFuturePeriod: true,
              name: '(RTEEN/Parenting) Projected date for completion',
              translatedName: 'Letsatsi la RTEEN/Parenting le tla phetheloa',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'PoxYSqq8Hgz',
              name: 'P&FC',
              translatedName: 'Tšebeletso a P&FC',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'O3mOdzWYmg3',
              name: '(P&FC) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho P&FC',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'WFscqdyjgUy',
              name: '(P&FC) Name of responsible external Person',
              translatedName: 'Motho ea ikarabellang ka ntle ho P&FC',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'fCDk1LxN484',
              allowFuturePeriod: true,
              name: '(P&FC) Projected date for completion',
              translatedName: 'Letsatsi la P&FC le tla phetheloa',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'exHDkX1gPiC',
              name: 'SHELTER',
              translatedName: 'Tšebeletso a SHELTER',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'MaBOowDgrFF',
              name: '(SHELTER) Name of responsible internal person',
              translatedName: 'Motho ea ikarabellang ka hare ho SHELTER',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'aVfUmmotSaB',
              name: '(SHELTER) Name of responsible external Person',
              translatedName: 'Motho ea ikarabellang ka ntle ho SHELTER',
              valueType: 'TEXT',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
          InputField(
              id: 'MDMmtTJTIyh',
              allowFuturePeriod: true,
              name: '(SHELTER) Projected date for completion',
              translatedName: 'Letsatsi la SHELTER le tla phetheloa',
              valueType: 'DATE',
              firstDate: firstDate,
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373)),
        ],
      ),
    ];
  }
}
