import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

class OvcServicesChildServiceProvision {
  static List<FormSection> getFormSections() {
    return [
      FormSection(
          id: 'Health',
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          color: Color(0xFF4D9E49),
          borderColor: Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'BYu8pI5kGXF',
              name: 'HIVSCREEN Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVSCREEN',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'u8r8p0a3JqU',
                name: 'HIVSCREEN Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa HIVSCREEN',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'W5lbgijaXA6',
                name: 'HIVSCREEN Comment',
                translatedName: 'Tlhaloso ea HIVSCREEN',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'JnqldNamliR',
              name: 'HTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'CNnzifTDF5a',
                name: 'HTS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HTS',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'sxlVgySosg3',
                name: 'HTS Comment',
                translatedName: 'Tlhaloso ea HTS',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'YFgrURiwirq',
              name: 'HIVTREAT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVTREAT',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'LtiZFxXw0Wc',
                name: 'HIVTREAT Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVTREAT',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'i9icxSZ8HCf',
                name: 'HIVTREAT Comment',
                translatedName: 'Tlhaloso ea HIVTREAT',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'HzI5X2yHef6',
              name: 'HIVS&D/HIV Messaging Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVS&D/HIV Messaging',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'GyG2HcLsVka',
                name: 'HIVS&D/HIV Messaging Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa HIVS&D/HIV Messaging',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'uU4TvD2O1uL',
              name: 'HIVS&D/HIV Messaging session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVS&D/HIV Messaging',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'y8ToqnbVz1o',
                name: 'HIVS&D/HIV Messaging Comment',
                translatedName: 'Tlhaloso ea HIVS&D/HIV Messaging',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'eqhzeRBMftZ',
              name: 'HEALTH Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HEALTH',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'F8x8QAoFQBO',
                name: 'HEALTH Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HEALTH',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'AStxMCkJhi5',
                name: 'HEALTH Comment',
                translatedName: 'Tlhaloso ea HEALTH',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'ESIjwQ9S6Ic',
              name: 'PRG&L Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PRG&L',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'EYv3aMwJOUN',
                name: 'PRG&L Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PRG&L',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'GISFLEttRtU',
                name: 'PRG&L Comment',
                translatedName: 'Tlhaloso ea PRG&L',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'r8wPQAog7PJ',
              name: 'SAIDS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SAIDS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'EgbO5h9cs5D',
                name: 'SAIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SAIDS',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'itTgPQ0OrMU',
                name: 'SAIDS Comment',
                translatedName: 'Tlhaloso ea SAIDS',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'UKczyQWCB0L',
              name: 'IMMUNIZE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea IMMUNIZE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'jsEr16lnber',
                name: 'IMMUNIZE Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa IMMUNIZE',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'wZLjymsKsuj',
                name: 'IMMUNIZE Comment',
                translatedName: 'Tlhaloso ea IMMUNIZE',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'KkqMjxjAR7g',
              name: 'MALNU Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea MALNU',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'gYAZrh9o1DB',
                name: 'MALNU Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa MALNU',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'Jxlug5I3kdu',
                name: 'MALNU Comment',
                translatedName: 'Tlhaloso ea MALNU',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'mRoO7kgpgVg',
              name: 'CCFLS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'CIRXgKGOmSI',
                name: 'CCFLS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa CCFLS',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'wfiqfXHUBde',
              name: 'CCFLS session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'YSsfKXdIRLG',
                name: 'CCFLS Comment',
                translatedName: 'Tlhaloso ea CCFLS',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'GNQ3gDA2CTI',
              name: 'STIMULATE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea STIMULATE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'oTSVSO3iHTk',
                name: 'STIMULATE Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa STIMULATE',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'PYMmQdzlPLJ',
              name: 'STIMULATE session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea STIMULATE',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'aDOvfQ1wdIX',
                name: 'STIMULATE Comment',
                translatedName: 'Tlhaloso ea STIMULATE',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'gSp9bgPW52L',
              name: 'TBSCREEN Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TBSCREEN',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'fVpcWBp0Ngp',
                name: 'TBSCREEN Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa TBSCREEN',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            
            InputField(
                id: 'pSkl6ibruvU',
                name: 'TBSCREEN Comment',
                translatedName: 'Tlhaloso ea TBSCREEN',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'mY7GqOTKtsQ',
              name: 'TBREFER Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TBREFER',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'h6obb1v1stw',
                name: 'TBREFER Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa TBREFER',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'kBivIQr6mrW',
                name: 'TBREFER Comment',
                translatedName: 'Tlhaloso ea TBREFER',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'zK7kMYpgPQn',
              name: 'FOODPREP Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FOODPREP',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'GtejBpkVvtD',
                name: 'FOODPREP Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa FOODPREP',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'F6z3SQxLskG',
              name: 'FOODPREP session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FOODPREP',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'g2X9vUL2d9m',
                name: 'FOODPREP Comment',
                translatedName: 'Tlhaloso ea FOODPREP',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'tnspdPfpuXm',
              name: 'FOODPREV Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FOODPREV',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'V1HnY5m2Pmv',
                name: 'FOODPREV Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa FOODPREV',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'YRUnLuPerwn',
              name: 'FOODPREV session number',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FOODPREV',
              valueType: 'TEXT',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'eXh6Gag1uwp',
                name: 'FOODPREV Comment',
                translatedName: 'Tlhaloso ea FOODPREV',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'QnFYeBNZlbf',
              name: 'FOODSUPP Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FOODSUPP',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'EnrZPBFxZuX',
                name: 'FOODSUPP Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa FOODSUPP',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'xdI5atw8DC4',
                name: 'FOODSUPP Comment',
                translatedName: 'Tlhaloso ea FOODSUPP',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373))
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: Color(0xFF0000FF),
          borderColor: Color(0xFF0000FF),
          inputFields: [
            InputField(
              id: 'KvLYMr8F4vg',
              name: 'OVCFUND Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea OVCFUND',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'hnMy2l2pB3z',
                name: 'OVCFUND Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa OVCFUND',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'TN5r1EFmHWz',
                name: 'OVCFUND Comment',
                translatedName: 'Tlhaloso ea OVCFUND',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'AnnOS2m6LZK',
              name: 'Savings Group Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SGROUP',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'UHWzhDsQdoB',
                name: 'Savings Group Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa Savings Group',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'WA8MAXBxaD1',
                name: 'Savings Group session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea SGROUP',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'xECpX8Vt1rT',
                name: 'Savings Group Comment',
                translatedName: 'Tlhaloso ea Savings Group',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'kcoDiGNXWpA',
              name: 'EST COOPRTVS Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea EST COOPRTVS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'qwmtkJDotBk',
                name: 'EST COOPRTVS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa EST COOPRTVS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'giA7cceTW8w',
                name: 'EST COOPRTVS Comment',
                translatedName: 'Tlhaloso ea EST COOPRTVS ',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'fgDPoYtifQI',
              name: 'FUNCT COOPRTVS Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea FUNCT COOPRTVS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'lbCCs00yuGQ',
                name: 'FUNCT COOPRTVS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FUNCT COOPRTVS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'TNmg7uRUWgC',
                name: 'FUNCT COOPRTVS Comment',
                translatedName: 'Tlhaloso ea FUNCT COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'cbqS6IoSbwI',
              name: 'MARKT COOPRTVS Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea MARKT COOPRTVS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0000FF),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'zKkaaSt1c8V',
                name: 'MARKT COOPRTVS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa MARKT COOPRTVS',
                valueType: 'DATE',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'KpUgwivl5Cr',
                name: 'MARKT COOPRTVS Comment',
                translatedName: 'Tlhaloso ea MARKT COOPRTVS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0000FF),
                labelColor: Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Safe',
          name: 'DOMAIN SAFE',
          translatedName: 'TSIRELETSO',
          color: Color(0xFF0F9587),
          borderColor: Color(0xFF0F9587),
          inputFields: [
            InputField(
              id: 'RNKOtUtLT4c',
              name: 'Singing to the LION Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SLION',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'sa79KxTFGFA',
                name: 'Singing to the LION Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa Singing to the LION',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'FAqGmEGN1sa',
                name: 'Singing to the LION session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea SLION',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'EB3JPVqMdb4',
                name: 'Singing to the LION Comment',
                translatedName: 'Tlhaloso ea Singing to the LION',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'GImA3HB9YK5',
              name: 'RTEEN/Parenting Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea RTEEN',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'fFuabYbLUjz',
                name: 'RTEEN/Parenting Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa RTEEN/Parenting',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'QBNhlIan0LR',
                name: 'RTEEN/Parenting session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea RTEEN',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'IFggJCXLYPD',
                name: 'RTEEN/Parenting Comment',
                translatedName: 'Tlhaloso ea RTEEN/Parenting',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'Fj2RbXsb8Yj',
              name: 'RKIDS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea RKIDS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'f90c5olxs5Z',
                name: 'RKIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa RKIDS',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'xbMtMJ9Uo5j',
                name: 'RKIDS session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea RKIDS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'EPwDypaz61A',
                name: 'RKIDS Comment',
                translatedName: 'Tlhaloso ea RKIDS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'rMtSykWZ4HB',
              name: 'VAC/VAC Messaging Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'qwnfgBG2web',
                name: 'VAC/VAC Messaging Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa VAC/VAC Messaging',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'YPImSLRMLWH',
                name: 'VAC/VAC Messaging session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'OMhFxj6SYhM',
                name: 'VAC/VAC Messaging Comment',
                translatedName: 'Tlhaloso ea VAC/VAC Messaging',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'QDFZ03HbjGj',
              name: 'VAC Legal Messaging Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea VAC Legal Messaging',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'Dw1xLXILErU',
                name: 'VAC Legal Messaging Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa VAC Legal Messaging',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'P4PMMDgWCSA',
                name: 'VAC Legal Messaging session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'KWk8waoLO7N',
                name: 'VAC Legal Messaging Comment',
                translatedName: 'Tlhaloso ea VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'cuy4Ai7mBbA',
              name: 'Survivors of Abuse Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SURVIVORS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'C5bhgqcq6Qn',
                name: 'Survivors of Abuse Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SURVIVORS',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'sONWFapy6yk',
                name: 'Survivors of Abuse session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea SURVIVORS',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'h10Iktl4KKR',
                name: 'Survivors of Abuse Comment',
                translatedName: 'Tlhaloso ea Survivors of Abuse',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'ysDSdiL7wNx',
              name: 'COUNSEL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea COUNSEL',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'pBVmFpsSGN7',
                name: 'COUNSEL Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa COUNSEL',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'LkQxvdt6YCw',
                name: 'COUNSEL session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea COUNSEL',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'XUoqvbk0uVH',
                name: 'COUNSEL Comment',
                translatedName: 'Tlhaloso ea COUNSEL',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'vj0R7ySdigX',
              name: 'FCARE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea FCARE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'yW0TrzEslYO',
                name: 'FCARE Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa FCARE',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'HtBtsU71Can',
                name: 'FCARE session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea FCARE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'tmi1jtKYZs0',
                name: 'FCARE Comment',
                translatedName: 'Tlhaloso ea FCARE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'JlRnllAlSk0',
              name: 'SHELTER Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SHELTER',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'VlOw6vrLsp5',
                name: 'SHELTER Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SHELTER',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'RcKIwnxrhqw',
                name: 'SHELTER session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea SHELTER',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'ONC3bpjq525',
                name: 'SHELTER Comment',
                translatedName: 'Tlhaloso ea SHELTER',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'UZJ9vqIabAY',
              name: 'ABUSE Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea ABUSE',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'pGDK3Y7tN2B',
                name: 'ABUSE Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa ABUSE',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'Gs4XVviJB3r',
                name: 'ABUSE session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea ABUSE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'U8h0daQzXXk',
                name: 'ABUSE Comment',
                translatedName: 'Tlhaloso ea ABUSE',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'gfKsz88uxtg',
              name: 'LEGALPROT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea LEGALPROT',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'P06od0qmlSR',
                name: 'LEGALPROT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa LEGALPROT',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'NwtohlveKHW',
                name: 'LEGALPROT session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea LEGALPROT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'iz4CvIFovsF',
                name: 'LEGALPROT Comment',
                translatedName: 'Tlhaloso ea LEGALPROT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'aGChpBlIzcd',
              name: 'BIRTHCERT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea BIRTHCERT',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF0F9587),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'AXLxNo9pz8c',
                name: 'BIRTHCERT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa BIRTHCERT',
                valueType: 'DATE',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'RTEBrgDTe02',
                name: 'BIRTHCERT session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'cb773khL7XB',
                name: 'BIRTHCERT Comment',
                translatedName: 'Tlhaloso ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: Color(0xFF0F9587),
                labelColor: Color(0xFF737373))
          ]),
      FormSection(
          id: 'Schooled',
          name: 'DOMAIN SCHOOLED',
          translatedName: 'TSA SEKOLO',
          color: Color(0xFF9B2BAE),
          borderColor: Color(0xFF9B2BAE),
          inputFields: [
            InputField(
              id: 'LcIB5EL3IjT',
              name: 'Aflatoun/teen Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea AFLAS',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'zYrrrFd48S5',
                name: 'Aflatoun/teen Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa Aflatoun/teen',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'g0WhpZC7Rhe',
                name: 'Aflatoun/teen session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea AFLAS',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'WVsVwfErZ7V',
                name: 'Aflatoun/teen Comment',
                translatedName: 'Tlhaloso ea Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'EYhFIkTpUS3',
              name: 'PTS4G Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4G',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'rM13n9K4vE7',
                name: 'PTS4G Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PTS4G',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'uVd1sxrd6C7',
                name: 'PTS4G session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4G',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'VlReEXXH1WN',
                name: 'PTS4G Comment',
                translatedName: 'Tlhaloso ea PTS4G',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'IiKUlAeSIE3',
              name: 'PTS4NG Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4NG',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'rUCb6Afcz9U',
                name: 'PTS4NG Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PTS4NG',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'p8Ha7w4plCe',
                name: 'PTS4NG session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea PTS4NG',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'sD0zbIksKTY',
                name: 'PTS4NG Comment',
                translatedName: 'Tlhaloso ea PTS4NG',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'hg2bpp1HqwU',
              name: 'HWCLUB Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HWCLUB',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'wB2jXLTYtDb',
                name: 'HWCLUB Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HWCLUB',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'cuLeuQsq7ZG',
                name: 'HWCLUB session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea HWCLUB',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'Riyr0nniCVo',
                name: 'HWCLUB Comment',
                translatedName: 'Tlhaloso ea HWCLUB',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'fvgPnlOD7e9',
              name: 'BURSARY Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea BURSARY',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'JFetYCY5tza',
                name: 'BURSARY Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa BURSARY',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'yuwtSD8EyoY',
                name: 'BURSARY Comment',
                translatedName: 'Tlhaloso ea BURSARY',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'MeMaUvt3O8j',
              name: 'SFEES Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SFEES',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'KZIjTeMl7sj',
                name: 'SFEES Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SFEES',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'KppYygPZ8BL',
                name: 'SFEES Comment',
                translatedName: 'Tlhaloso ea SFEES',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'WQlWXUmYjI2',
              name: 'SMATERIAL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SMATERIAL',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'gAMv1jxS0rh',
                name: 'SMATERIAL Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SMATERIAL',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'CxREUNzKxHB',
                name: 'SMATERIAL Comment',
                translatedName: 'Tlhaloso ea SMATERIAL',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
              id: 'Zc0M1jsbfyA',
              name: 'REENROL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea REENROL',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF9B2BAE),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'mLjRp8wJ8aW',
                name: 'REENROL Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa REENROL',
                valueType: 'DATE',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'QCbFgssCzeF',
                name: 'REENROL Comment',
                translatedName: 'Tlhaloso ea REENROL',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373))
          ]),
      FormSection(
          name: 'Other Activities',
          color: Color(0xFF4D9E49),
          borderColor: Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'TSx4O9Tf5v2',
              name: 'OTHER ACTIVITIES Service provided',
              valueType: 'TRUE_ONLY',
              inputColor: Color(0xFF4D9E49),
              labelColor: Color(0xFF737373),
            ),
            InputField(
                id: 'x5VlMVD2a4E',
                name: 'OTHER ACTIVITIES Service Provision Date',
                valueType: 'DATE',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'mPMxntJR5Qy',
                name: 'OTHER ACTIVITIES session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea OTHER ACTIVITIES',
                valueType: 'TEXT',
                inputColor: Color(0xFF9B2BAE),
                labelColor: Color(0xFF737373)),
            InputField(
                id: 'rJaHpLnWvfg',
                name: 'OTHER ACTIVITIES Comment',
                valueType: 'TEXT',
                inputColor: Color(0xFF4D9E49),
                labelColor: Color(0xFF737373)),
          ])
    ];
  }
}
