import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';
// single, group house =< caregiver
class OvcServicesChildCasePlanGap {
  static List<FormSection> getFormSections({
    required String firstDate,
  }) {
    //Date for HIVS&D to be completed
    return [
      FormSection(
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          id: 'Health',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
                id: 'cx4xBY4jZXM',
                name: 'HIV S&D',
                translatedName: 'Tšebeletso ea HIV S&D',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'b6hvMQuH3oJ',
                name: '(HIV S&D) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIV S&D',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iy0KZ7K4qld',
                name: '(HIV S&D) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIV S&D',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'SIEeRmPm0Q0',
                allowFuturePeriod: true,
                name: '(HIV S&D) Projected date for completion',
                translatedName: 'Letsatsi la HIV S&D le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'hJUuQ648wVF',
                name: 'CCFLS',
                translatedName: 'Tšebeletso ea CCFLS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'aYFP1w8y96h',
                name: '(CCFLS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho CCFLS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'QfqDdhGC5vR',
                name: '(CCFLS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho CCFLS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'o37J0mUPmg6',
                allowFuturePeriod: true,
                name: '(CCFLS) Projected date for completion',
                translatedName: 'Letsatsi la CCFLS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'BJrrrqQqwQO',
                name: 'CHILD STIMULATION ',
                translatedName: 'Tšebeletso ea CHILD STIMULATION ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'joBt3RJP76y',
                name: '(CHILD STIMULATION ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho CHILD STIMULATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'wQDSOL4EJ8G',
                name: '(CHILD STIMULATION ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho CHILD STIMULATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'S6O1OxbLfzz',
                allowFuturePeriod: true,
                name: '(CHILD STIMULATION ) Projected date for completion',
                translatedName: 'Letsatsi la CHILD STIMULATION  le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
             InputField(
                id: 'LswSBpMoG5C',
                name: 'TB SCREENING ',
                translatedName: 'Tšebeletso ea TB SCREENING ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'RUoYTsLHBdY',
                name: '(TB SCREENING ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho TB SCREENING ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'FAJpI6PUK8w',
                name: '(TB SCREENING ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho TB SCREENING ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'ziQvzVbjmcb',
                allowFuturePeriod: true,
                name: '(TB SCREENING ) Projected date for completion',
                translatedName: 'Letsatsi la TB SCREENING  le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          InputField(
                id: 'AwWKp6KmqgY',
                name: 'FOOD PREV ',
                translatedName: 'Tšebeletso ea FOOD PREV ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cXCdR7BvrSM',
                name: '(FOOD PREV ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD PREV ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'u8yn7sY5eOX',
                name: '(FOOD PREV ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD PREV ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'Mu0LxlAOoSp',
                allowFuturePeriod: true,
                name: '(FOOD PREV ) Projected date for completion',
                translatedName: 'Letsatsi la FOOD PREV  le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
             InputField(
                id: 'JSQ3xP1NhuN',
                name: 'FOOD PREP ',
                translatedName: 'Tšebeletso ea FOOD PREP',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'k6jzyzGOu5Y',
                name: '(FOOD PREP ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD PREP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HrCyUkuZath',
                name: '(FOOD PREP ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD PREP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'MdmCqSwcrlk',
                allowFuturePeriod: true,
                name: '(FOOD PREP ) Projected date for completion',
                translatedName: 'Letsatsi la FOOD PREP le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'DQxqyncQtwm',
                name: 'TIPPY TAP ',
                translatedName: 'Tšebeletso ea TIPPY TAP',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'P4I6rK6Xqxw',
                name: '(TIPPY TAP ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho TIPPY TAP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WFKe1YpH1uK',
                name: '(TIPPY TAP ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho TIPPY TAP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'YJXb5rSVP0L',
                allowFuturePeriod: true,
                name: '(TIPPY TAP ) Projected date for completion',
                translatedName: 'Letsatsi la TIPPY TAP le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qTf8VSoojJ2',
                name: 'SOACKAGE PIT ',
                translatedName: 'Tšebeletso ea SOACKAGE PIT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ontonbgTJ8k',
                name: '(SOACKAGE PIT ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SOACKAGE PIT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AjYKLfIQPtT',
                name: '(SOACKAGE PIT ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SOACKAGE PIT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'M2Aqvn027cd',
                allowFuturePeriod: true,
                name: '(SOACKAGE PIT ) Projected date for completion',
                translatedName: 'Letsatsi la SOACKAGE PIT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Hvq9oisH7Gt',
                name: 'WASH MESSAGING ',
                translatedName: 'Tšebeletso ea WASH MESSAGING',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ue6xLPEURqt',
                name: '(WASH MESSAGING ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SWASH MESSAGING ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vIbKIUgzBU4',
                name: '(WASH MESSAGING ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho WASH MESSAGING ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'tQ3pKyJ0X9d',
                allowFuturePeriod: true,
                name: '( WASH MESSAGING ) Projected date for completion',
                translatedName: 'Letsatsi la WASH MESSAGING le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HKCv7lkLexo',
                name: 'HIV ADHERANCE SUPPORT ',
                translatedName: 'Tšebeletso ea HIV ADHERANCE SUPPORT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd3X7sRgkQkl',
                name: '(HIV ADHERANCE SUPPORT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIV ADHERANCE SUPPORT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd8vFkGjiux4',
                name: '(HIV ADHERANCE SUPPORT ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIV ADHERANCE SUPPORT ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JzlLk2tW4xh',
                allowFuturePeriod: true,
                name: '( HIV ADHERANCE SUPPORT ) Projected date for completion',
                translatedName: 'Letsatsi la HIV ADHERANCE SUPPORT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                    InputField(
                id: 'XoSPWmpWXCy',
                name: 'HTS',
                translatedName: 'Tšebeletso a HTS ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vqf67Edjw4y',
                name: '(HTS) Name of responsible internal Person',
                translatedName: 'Motho ea ikarabellang ka hare ho HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bQtXR6iQyo8',
                name: '(HTS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iFv7FJeG3V1',
                allowFuturePeriod: true,
                name: '(HTS) Projected date for completion',
                translatedName: 'Letsatsi la HTS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                InputField(
                id: 'ylSjcj6cv42',
                name: 'HIVTREAT',
                translatedName: 'Tšebeletso a HIVTREAT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'elqeNdaYNTS',
                name: '(HIVTREAT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'IhzyIy3tzo0',
                name: '(HIVTREAT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qMrZcC7VvCV',
                allowFuturePeriod: true,
                name: '(HIVTREAT) Projected date for completion',
                translatedName: 'Letsatsi la HIVTREAT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                            InputField(
                id: 'd2vXxEPeCq7',
                name: 'PRG&L',
                translatedName: 'Tšebeletso a PRG&L',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GnsYKEE2fnr',
                name: '(PRG&L) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'X2CA3iQZU74',
                name: '(PRG&L) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kpzlTeM0673',
                allowFuturePeriod: true,
                name: '(PRG&L) Projected date for completion',
                translatedName: 'Letsatsi la PRG&L le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dTFLFtUUeEK',
                name: 'SAIDS',
                translatedName: 'Tšebeletso a SAIDS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'emAJOTWYHVq',
                name: '(SAIDS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'lwa1qFrFISz',
                name: '(SAIDS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jlu7TDN7khJ',
                allowFuturePeriod: true,
                name: '(SAIDS) Projected date for completion',
                translatedName: 'Letsatsi la SAIDS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
  
            InputField(
                id: 'x4yAqv4z2Xv',
                name: 'IMMUNIZATION',
                translatedName: 'Tšebeletso a IMMUNIZATION',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'tYYpfnshIvw',
                name: '(IMMUNIZATION) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho IMMUNIZATION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bn0EIFjqXes',
                name: '(IMMUNIZATION) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho IMMUNIZATION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'eTDE6zroxBC',
                allowFuturePeriod: true,
                name: '(IMMUNIZATION) Projected date for completion',
                translatedName: 'Letsatsi la IMMUNIZATION le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AM9oJCOHM7f',
                name: 'MALNUTRITION',
                translatedName: 'Tšebeletso a MALNUTRITION',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SOPRtGCfa5Z',
                name: '(MALNUTRITION) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho MALNUTRITION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'B9YT3pHNGOg',
                name: '(MALNUTRITION) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho MALNUTRITION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'RoJrwtEhpzk',
                allowFuturePeriod: true,
                name: '(MALNUTRITION) Projected date for completion',
                translatedName: 'Letsatsi la MALNUTRITION le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'gCKoJgBFdob',
                name: 'TB REFFER',
                translatedName: 'Tšebeletso ea TB REFFER',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'mWwizkG0EK2',
                name: '(TB REFFER) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho TB REFFER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'nUIvqATNc7A',
                name: '(TB REFFER) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho TB REFFER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'VmuVgr4tfor',
                allowFuturePeriod: true,
                name: '(TB REFFER) Projected date for completion',
                translatedName: 'Letsatsi la TB REFFER le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'uvJV4WGc5ct',
                name: 'FOOD SUPPLIMENTS',
                translatedName: 'Tšebeletso ea FOOD SUPPLIMENTS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'mvdraUOCfKA',
                name: '(FOOD SUPPLIMENTS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD SUPPLIMENTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'aZ1ogdjGHUV',
                name: '(FOOD SUPPLIMENTS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD SUPPLIMENTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'F2IOqOr4EuV',
                allowFuturePeriod: true,
                name: '(FOOD SUPPLIMENTS) Projected date for completion',
                translatedName: 'Letsatsi la FOOD SUPPLIMENTS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EaJTFrklMo5',
                name: 'FOOD SUPPORT',
                translatedName: 'Tšebeletso ea FOOD SUPPORT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rHgxOKM91wi',
                name: '(FOOD SUPPORT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOOD SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'v00dsDvhCRu',
                name: '(FOOD SUPPORT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOOD SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WAq2HJHXZYS',
                allowFuturePeriod: true,
                name: '(FOOD SUPPORT) Projected date for completion',
                translatedName: 'Letsatsi la FOOD SUPPORT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  InputField(
                id: 'AxtahhoHcXV',
                name: 'HEALTH',
                translatedName: 'Tšebeletso a HEALTH',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'G6GkSeccLmB',
                name: '(HEALTH) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HEALTH',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GULhHDCXRvz',
                name: '(HEALTH) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HEALTH',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ugZKkd3UMNF',
                allowFuturePeriod: true,
                name: '(HEALTH) Projected date for completion',
                translatedName: 'Letsatsi la HEALTH le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
                  ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: const Color(0xFF0000FF),
          borderColor: const Color(0xFF0000FF),
          inputFields: [

   InputField(
                id: 'e6NV2ZAzFEh',
                name: 'SILC',
                translatedName: 'Tšebeletso ea SILC',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JtfKB58MvNK',
                name: '(SILC) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MMjndp2xsoQ',
                name: '(SILC) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SILC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Hdf3EtTGfAb',
                allowFuturePeriod: true,
                name: '(SILC) Projected date for completion',
                translatedName: 'Letsatsi la SILC le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yPP7lkomNfK',
                name: 'SAVINGS GROUP',
                translatedName: 'Tšebeletso a SAVINGS GROUP',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ZQ6jDrZ54ic',
                name: '(SAVINGS GROUP) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SAVINGS GROUP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XhG2eidZKCN',
                name: '(SAVINGS GROUP) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SAVINGS GROUP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vJx6vWPxGsJ',
                allowFuturePeriod: true,
                name: '(SAVINGS GROUP) Projected date for completion',
                translatedName: 'Letsatsi la SAVINGS GROUP le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
             InputField(
                id: 'kvF996ugmMl',
                name: 'FINANCIAL EDUCATION ',
                translatedName: 'Tšebeletso ea FINANCIAL EDUCATION ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OMtcDA7tcVL',
                name: '(FINANCIAL EDUCATION ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Mz24UpWclb3',
                name: '(FINANCIAL EDUCATION ) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'zVCkEJuy2t8',
                allowFuturePeriod: true,
                name: '(FINANCIAL EDUCATION ) Projected date for completion',
                translatedName: 'Letsatsi la FINANCIAL EDUCATION le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WrjNxZBVHCL',
                name: 'KPLOT',
                translatedName: 'Tšebeletso ea KPLOT ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'NWBZilCPutW',
                name: '(KPLOT ) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho KPLOT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'boUUP8UeWDL',
                name: '(KPLOT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho KPLOT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd3k97F0fS2y',
                allowFuturePeriod: true,
                name: '(KPLOT) Projected date for completion',
                translatedName: 'Letsatsi la KPLOT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),

  ]),
      FormSection(
          id: 'Safe',
          name: 'DOMAIN SAFE',
          translatedName: 'TSIRELETSO',
          color: const Color(0xFF0F9587),
          borderColor: const Color(0xFF0F9587),
          inputFields: [

        InputField(
                id: 'uQiyym8SEvd',
                name: 'Singing to the LION',
                translatedName: 'Tšebeletso a Singing to the LION',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GjIU252Rcvq',
                name:
                    '(Singing to the LION) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SLION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'meOOSrOPoLB',
                name:
                    '(Singing to the LION) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SLION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MEFwYLoRyPR',
                allowFuturePeriod: true,
                name: '(Singing to the LION ) Projected date for completion',
                translatedName:
                    'Letsatsi la Singing to the LION le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WiPTQhWLVU1',
                name: 'RTEEN/Parenting',
                translatedName: 'Tšebeletso a RTEEN/Parenting',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'E2CWztOcx2X',
                name: '(RTEEN/Parenting) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho RTEEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'xFXc0oacTEb',
                name: '(RTEEN/Parenting) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho RTEEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'BpLk6ruSL7e',
                allowFuturePeriod: true,
                name: '(RTEEN/Parenting) Projected date for completion',
                translatedName: 'Letsatsi la RTEEN/Parenting le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'neF08iYV9Os',
                name: 'RKIDS',
                translatedName: 'Tšebeletso a RKIDS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kGQwyzaP5Km',
                name: '(RKIDS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho RKIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OyeIR1fmV4s',
                name: '(RKIDS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho RKIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Y1ta8eJAWBT',
                allowFuturePeriod: true,
                name: '(RKIDS) Projected date for completion',
                translatedName: 'Letsatsi la RKIDS le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
           InputField(
                id: 'PoxYSqq8Hgz',
                name: 'P&FC',
                translatedName: 'Tšebeletso a P&FC',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'O3mOdzWYmg3',
                name: '(P&FC) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho P&FC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WFscqdyjgUy',
                name: '(P&FC) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho P&FC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'fCDk1LxN484',
                allowFuturePeriod: true,
                name: '(P&FC) Projected date for completion',
                translatedName: 'Letsatsi la P&FC le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
                 InputField(
                id: 'aPmPhwm8Zln',
                name: 'VAC/VAC Messaging',
                translatedName: 'Tšebeletso a VAC/VAC Messaging',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jKqWohAPqyW',
                name: '(VAC/VAC Messaging) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho VAC/VAC Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'U8jnyQsnfBD',
                name: '(VAC/VAC Messaging) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho VAC/VAC Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'wGrQeSydiwd',
                allowFuturePeriod: true,
                name: '(VAC/VAC Messaging) Projected date for completion',
                translatedName:
                    'Letsatsi la VAC/VAC Messaging le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
   InputField(
                id: 'AaqeRcyjbyS',
                name: 'VAC Legal Messaging',
                translatedName: 'Tšebeletso a VAC Legal Messaging',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'TizNGPP6e1d',
                name:
                    '(VAC Legal Messaging) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Q7GxvZD6h99',
                name:
                    '(VAC Legal Messaging) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'A4xYu8BYOg7',
                allowFuturePeriod: true,
                name: '(VAC Legal Messaging) Projected date for completion',
                translatedName:
                    'Letsatsi la VAC Legal Messaging le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
        
             InputField(
                id: 'Ccp4Odlh3BE',
                name: 'COUNSEL',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kGoKVtkQxvk',
                name: '(COUNSEL) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho COUNSEL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yoI0bu18mPo',
                name: '(COUNSEL) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho COUNSEL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Io9nnYXCvWR',
                allowFuturePeriod: true,
                name: '(COUNSEL) Projected date for completion',
                translatedName: 'Letsatsi la COUNSEL le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
        InputField(
                id: 'hS7aONLz2cq',
                name: 'BIRTHCERT',
                translatedName: 'Tšebeletso a BIRTHCERT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'LDH3TLjHUYK',
                name: '(BIRTHCERT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Pd5CyDu2Z54',
                name: '(BIRTHCERT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SvkvfRNqyh2',
                allowFuturePeriod: true,
                name: '(BIRTHCERT) Projected date for completion',
                translatedName: 'Letsatsi la BIRTHCERT le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WdZ3PnW5yV6',
                name: 'LEGAL PROTECTION ',
                translatedName: 'Tšebeletso a LEGAL PROTECTION ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dJR6GJyHCTr',
                name:
                    '(LEGAL PROTECTION ) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho LEGAL PROTECTION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cu1UkUUTbME',
                name:
                    '(LEGAL PROTECTION ) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho LEGAL PROTECTION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OIw6D3I6BmY',
                allowFuturePeriod: true,
                name: '(LEGAL PROTECTION) Projected date for completion',
                translatedName:
                    'Letsatsi la LEGAL PROTECTION  le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
 ]),
      FormSection(
          id: 'Schooled',
          name: 'DOMAIN SCHOOLED',
          translatedName: 'TSA SEKOLO',
          color: const Color(0xFF9B2BAE),
          borderColor: const Color(0xFF9B2BAE),
          inputFields: [
             InputField(
                id: 'Cb8qzfdrg7d',
                name: 'Aflatoun/teen',
                translatedName: 'Tšebeletso a Aflatoun/teen',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JiqD0sYv7pH',
                name: '(Aflatoun/teen) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vqmvjogGeX5',
                name: '(Aflatoun/teen) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HeoYwEJukC8',
                allowFuturePeriod: true,
                name: '(Aflatoun/teen) Projected date for completion',
                translatedName: 'Letsatsi la Aflatoun/teen le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),

       InputField(
                id: 'X47zxNAqMv0',
                name: 'HOMEWORK CLUB',
                translatedName: 'Tšebeletso a HOMEWORK CLUB',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kfcqLf2d2dc',
                name: '(HOMEWORK CLUB) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho HOMEWORK CLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ewpLauNhb8N',
                name: '(HOMEWORK CLUB) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho HOMEWORK CLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rPhOdwWvfOA',
                allowFuturePeriod: true,
                name: '(HOMEWORK CLUB) Projected date for completion',
                translatedName: 'Letsatsi la HOMEWORK CLUB le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
       InputField(
                id: 'qraZh4n14S4',
                name: 'HOMEWORK CLUB',
                translatedName: 'Tšebeletso a HOMEWORK CLUB',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dSS3xEVkH26',
                name: '(HOMEWORK CLUB) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho HOMEWORK CLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JXx3FiIQe08',
                name: '(HOMEWORK CLUB) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho HOMEWORK CLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ZwGE57BjVdJ',
                allowFuturePeriod: true,
                name: '(HOMEWORK CLUB) Projected date for completion',
                translatedName: 'Letsatsi la HOMEWORK CLUB le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
    InputField(
                id: 'q2N7p3UbvSF',
                name: 'SMATERIAL',
                translatedName: 'Tšebeletso a SMATERIAL',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XFY4FxA7ymC',
                name: '(SMATERIAL) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SMATERIAL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rjKp0pEFJ2L',
                name: '(SMATERIAL) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SMATERIAL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Gw1wRcsPemn',
                allowFuturePeriod: true,
                name: '(SMATERIAL) Projected date for completion',
                translatedName: 'Letsatsi la SMATERIAL le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
  InputField(
                id: 'NcMANzhhphO',
                name: 'REENROL',
                translatedName: 'Tšebeletso a REENROL',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'fT9sHAd6Gvw',
                name: '(REENROL) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho REENROL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'lO7yfY3mBYB',
                name: '(REENROL) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho REENROL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GhPb5Acr00X',
                allowFuturePeriod: true,
                name: '(REENROL) Projected date for completion',
                translatedName: 'Letsatsi la REENROL le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),

  InputField(
                id: 'TdReJf2LTXA',
                name: 'SFEES',
                translatedName: 'Tšebeletso a SFEES',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EonyCjxIh5l',
                name: '(SFEES) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SFEES',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'meR35m2WVNZ',
                name: '(SFEES) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SFEES',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'YIFHsUgTAlI',
                allowFuturePeriod: true,
                name: '(SFEES) Projected date for completion',
                translatedName: 'Letsatsi la SFEES le tla phetheloa',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),]),

    ];
  }
}
