import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

class OvcServicesChildCasePlanGap {
  static List<FormSection> getFormSections() {
    return [
      FormSection(
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          id: 'Health',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
                id: 'QjlTTO5KAIf',
                name: 'Identified need/Gap',
                translatedName: 'Litlhoko kapa likhahello tse hloauoeng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yJQi4cbzeBF',
                name: 'HIVSCREEN',
                translatedName: 'Tšebeletso ea HIVSCREEN',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iWH5MhwPSbD',
                name: '(HIVSCREEN) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIVSCREEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'H4TLyWdOdrI',
                name: '(HIVSCREEN) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIVSCREEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'DqlxkJ0dMA2',
                allowFuturePeriod: true,
                name: '(HIVSCREEN) Projected date for completion',
                translatedName: 'Letsatsi la HIVSCREEN le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XoSPWmpWXCy',
                name: 'HTS',
                translatedName: 'Tšebeletso a HTS ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vqf67Edjw4y',
                name: '(HTS) Name of responsible internal Person',
                translatedName: 'Motho ea ikarabellang ka hare ho HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bQtXR6iQyo8',
                name: '(HTS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iFv7FJeG3V1',
                allowFuturePeriod: true,
                name: '(HTS) Projected date for completion',
                translatedName: 'Letsatsi la HTS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ylSjcj6cv42',
                name: 'HIVTREAT',
                translatedName: 'Tšebeletso a HIVTREAT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'elqeNdaYNTS',
                name: '(HIVTREAT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'IhzyIy3tzo0',
                name: '(HIVTREAT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qMrZcC7VvCV',
                allowFuturePeriod: true,
                name: '(HIVTREAT) Projected date for completion',
                translatedName: 'Letsatsi la HIVTREAT le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cx4xBY4jZXM',
                name: 'HIVS&D/HIV Messaging',
                translatedName: 'Tšebeletso a HIVS&D/HIV Messaging ',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'b6hvMQuH3oJ',
                name:
                    '(HIVS&D/HIV Messaging) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho HIVS&D/HIV Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iy0KZ7K4qld',
                name:
                    '(HIVS&D/HIV Messaging) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho HIVS&D/HIV Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SIEeRmPm0Q0',
                allowFuturePeriod: true,
                name: '(HIVS&D/HIV Messaging) Projected date for completion',
                translatedName:
                    'Letsatsi la HIVS&D/HIV Messaging le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AxtahhoHcXV',
                name: 'HEALTH',
                translatedName: 'Tšebeletso a HEALTH',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'G6GkSeccLmB',
                name: '(HEALTH) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HEALTH',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GULhHDCXRvz',
                name: '(HEALTH) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HEALTH',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ugZKkd3UMNF',
                allowFuturePeriod: true,
                name: '(HEALTH) Projected date for completion',
                translatedName: 'Letsatsi la HEALTH le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'd2vXxEPeCq7',
                name: 'PRG&L',
                translatedName: 'Tšebeletso a PRG&L',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GnsYKEE2fnr',
                name: '(PRG&L) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'X2CA3iQZU74',
                name: '(PRG&L) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kpzlTeM0673',
                allowFuturePeriod: true,
                name: '(PRG&L) Projected date for completion',
                translatedName: 'Letsatsi la PRG&L le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dTFLFtUUeEK',
                name: 'SAIDS',
                translatedName: 'Tšebeletso a SAIDS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'emAJOTWYHVq',
                name: '(SAIDS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'lwa1qFrFISz',
                name: '(SAIDS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jlu7TDN7khJ',
                allowFuturePeriod: true,
                name: '(SAIDS) Projected date for completion',
                translatedName: 'Letsatsi la SAIDS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'x4yAqv4z2Xv',
                name: 'IMMUNIZE',
                translatedName: 'Tšebeletso a IMMUNIZE',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'tYYpfnshIvw',
                name: '(IMMUNIZE) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho IMMUNIZE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bn0EIFjqXes',
                name: '(IMMUNIZE) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho IMMUNIZE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'eTDE6zroxBC',
                allowFuturePeriod: true,
                name: '(IMMUNIZE) Projected date for completion',
                translatedName: 'Letsatsi la IMMUNIZE le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AM9oJCOHM7f',
                name: 'MALNU',
                translatedName: 'Tšebeletso a MALNU',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SOPRtGCfa5Z',
                name: '(MALNU) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho MALNU',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'B9YT3pHNGOg',
                name: '(MALNU) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho MALNU',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'RoJrwtEhpzk',
                allowFuturePeriod: true,
                name: '(MALNU) Projected date for completion',
                translatedName: 'Letsatsi la MALNU le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'hJUuQ648wVF',
                name: 'CCFLS',
                translatedName: 'Tšebeletso a CCFLS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'DQab5Id3WMj',
                name: '(CCFLS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho CCFLS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'QfqDdhGC5vR',
                name: '(CCFLS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho CCFLS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'o37J0mUPmg6',
                allowFuturePeriod: true,
                name: '(CCFLS) Projected date for completion',
                translatedName: 'Letsatsi la CCFLS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'BJrrrqQqwQO',
                name: 'STIMULATE',
                translatedName: 'Tšebeletso a STIMULATE',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'c5vtF9QMiVU',
                name: '(STIMULATE) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho STIMULATE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'wQDSOL4EJ8G',
                name: '(STIMULATE) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho STIMULATE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'S6O1OxbLfzz',
                allowFuturePeriod: true,
                name: '(STIMULATE) Projected date for completion',
                translatedName: 'Letsatsi la STIMULATE le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'LswSBpMoG5C',
                name: 'TBSCREEN',
                translatedName: 'Tšebeletso a TBSCREEN',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Zdv3luz9Fja',
                name: '(TBSCREEN) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho TBSCREEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'FAJpI6PUK8w',
                name: '(TBSCREEN) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho TBSCREEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ziQvzVbjmcb',
                allowFuturePeriod: true,
                name: '(TBSCREEN) Projected date for completion',
                translatedName: 'Letsatsi la TBSCREEN le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'gCKoJgBFdob',
                name: 'TBREFER',
                translatedName: 'Tšebeletso a TBREFER',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'zVUhTogG1qE',
                name: '(TBREFER) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho TBREFER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'nUIvqATNc7A',
                name: '(TBREFER) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho TBREFER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'VmuVgr4tfor',
                allowFuturePeriod: true,
                name: '(TBREFER) Projected date for completion',
                translatedName: 'Letsatsi la TBREFER le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JSQ3xP1NhuN',
                name: 'FOODPREP',
                translatedName: 'Tšebeletso ea FOODPREP',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'DWIqhVfMZrD',
                name: '(FOODPREP) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOODPREP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HrCyUkuZath',
                name: '(FOODPREP) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOODPREP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MdmCqSwcrlk',
                allowFuturePeriod: true,
                name: '(FOODPREP) Projected date for completion',
                translatedName: 'Letsatsi la FOODPREP le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AwWKp6KmqgY',
                name: 'FOODPREV',
                translatedName: 'Tšebeletso a FOODPREV',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jvxeGCV3VZf',
                name: '(FOODPREV) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOODPREV',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'u8yn7sY5eOX',
                name: '(FOODPREV) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOODPREV',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Mu0LxlAOoSp',
                allowFuturePeriod: true,
                name: '(FOODPREV) Projected date for completion',
                translatedName: 'Letsatsi la FOODPREV le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EaJTFrklMo5',
                name: 'FOODSUPP',
                translatedName: 'Tšebeletso a FOODSUPP',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'whcEPShYGkD',
                name: '(FOODSUPP) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FOODSUPP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'v00dsDvhCRu',
                name: '(FOODSUPP) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FOODSUPP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WAq2HJHXZYS',
                allowFuturePeriod: true,
                name: '(FOODSUPP) Projected date for completion',
                translatedName: 'Letsatsi la FOODSUPP le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373))
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: const Color(0xFF0000FF),
          borderColor: const Color(0xFF0000FF),
          inputFields: [
            InputField(
                id: 'QjlTTO5KAIf',
                name: 'Identified need/Gap',
                translatedName: 'Litlhoko kapa likhahello tse hloauoeng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HsxFZOuV4oZ',
                name: 'OVCFUND',
                translatedName: 'Tšebeletso a OVCFUND',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'KKZBSXc1Sg3',
                name: '(OVCFUND) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho OVCFUND',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'DdNC3FdhhsW',
                name: '(OVCFUND) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho OVCFUND',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'tRxPMAXY6VC',
                allowFuturePeriod: true,
                name: '(OVCFUND) Projected date for completion',
                translatedName: 'Letsatsi la OVCFUND le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yPP7lkomNfK',
                name: 'Savings Group',
                translatedName: 'Tšebeletso a Savings Group',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ZQ6jDrZ54ic',
                name: '(Savings Group) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SGROUP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XhG2eidZKCN',
                name: '(Savings Group) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SGROUP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vJx6vWPxGsJ',
                allowFuturePeriod: true,
                name: '(Savings Group) Projected date for completion',
                translatedName: 'Letsatsi la Savings Group le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iiJpQsEE4qx',
                name: 'EST COOPRTVS',
                translatedName: 'Tšebeletso a EST COOPRTVS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'xse9M31M9z1',
                name: '(EST COOPRTVS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho EST COOPRTVS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'uLi7eqd0eEy',
                name: '(EST COOPRTVS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho EST COOPRTVS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'nIoqbMHf3AS',
                allowFuturePeriod: true,
                name: '(EST COOPRTVS) Projected date for completion',
                translatedName: 'Letsatsi la EST COOPRTVS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ithLHgsAoxs',
                name: 'FUNCT COOPRTVS',
                translatedName: 'Tšebeletso a FUNCT COOPRTVS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cKJggm2OXFQ',
                name: '(FUNCT COOPRTVS) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho FUNCT COOPRTVS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'NUXAxwvM3FE',
                name: '(FUNCT COOPRTVS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho COOPTRVTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kCoBEKqJelO',
                allowFuturePeriod: true,
                name: '(FUNCT COOPRTVS) Projected date for completion',
                translatedName: 'Letsatsi la FUNCT COOPRTVS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JqGGsDlZh8T',
                name: 'MARKT COOPRTVS',
                translatedName: 'Tšebeletso a MARKT COOPRTVS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'a9geBDwDmXA',
                name: '(MARKT COOPRTVS) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho MARKT COOPRTVS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 's5mJvzRyfmW',
                name: '(MARKT COOPRTVS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho MARKT COOP',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XODRLh84TdQ',
                allowFuturePeriod: true,
                name: '(MARKT COOPRTVS) Projected date for completion',
                translatedName: 'Letsatsi la MARKT COOPRTVS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Safe',
          name: 'DOMAIN SAFE',
          translatedName: 'TSIRELETSO',
          color: const Color(0xFF0F9587),
          borderColor: const Color(0xFF0F9587),
          inputFields: [
            InputField(
                id: 'QjlTTO5KAIf',
                name: 'Identified need/Gap',
                translatedName: 'Litlhoko kapa likhahello tse hloauoeng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'uQiyym8SEvd',
                name: 'Singing to the LION',
                translatedName: 'Tšebeletso a Singing to the LION',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GjIU252Rcvq',
                name:
                    '(Singing to the LION) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SLION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'meOOSrOPoLB',
                name:
                    '(Singing to the LION) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SLION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MEFwYLoRyPR',
                allowFuturePeriod: true,
                name: '(Singing to the LION ) Projected date for completion',
                translatedName:
                    'Letsatsi la Singing to the LION le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WiPTQhWLVU1',
                name: 'RTEEN/Parenting',
                translatedName: 'Tšebeletso a RTEEN/Parenting',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'E2CWztOcx2X',
                name: '(RTEEN/Parenting) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho RTEEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'xFXc0oacTEb',
                name: '(RTEEN/Parenting) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho RTEEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'BpLk6ruSL7e',
                allowFuturePeriod: true,
                name: '(RTEEN/Parenting) Projected date for completion',
                translatedName: 'Letsatsi la RTEEN/Parenting le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'neF08iYV9Os',
                name: 'RKIDS',
                translatedName: 'Tšebeletso a RKIDS',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kGQwyzaP5Km',
                name: '(RKIDS) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho RKIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OyeIR1fmV4s',
                name: '(RKIDS) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho RKIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Y1ta8eJAWBT',
                allowFuturePeriod: true,
                name: '(RKIDS) Projected date for completion',
                translatedName: 'Letsatsi la RKIDS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'aPmPhwm8Zln',
                name: 'VAC/VAC Messaging',
                translatedName: 'Tšebeletso a VAC/VAC Messaging',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'jKqWohAPqyW',
                name: '(VAC/VAC Messaging) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho VAC/VAC Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'U8jnyQsnfBD',
                name: '(VAC/VAC Messaging) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho VAC/VAC Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'wGrQeSydiwd',
                allowFuturePeriod: true,
                name: '(VAC/VAC Messaging) Projected date for completion',
                translatedName:
                    'Letsatsi la VAC/VAC Messaging le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AaqeRcyjbyS',
                name: 'VAC Legal Messaging',
                translatedName: 'Tšebeletso a VAC Legal Messaging',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'TizNGPP6e1d',
                name:
                    '(VAC Legal Messaging) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Q7GxvZD6h99',
                name:
                    '(VAC Legal Messaging) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'A4xYu8BYOg7',
                allowFuturePeriod: true,
                name: '(VAC Legal Messaging) Projected date for completion',
                translatedName:
                    'Letsatsi la VAC Legal Messaging le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Vd8dV7OweWB',
                name: 'Survivors of Abuse',
                translatedName: 'Tšebeletso a Survivors of Abuse',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'UDYd31rUKgN',
                name: '(SURVIVORS) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho Survivors of Abuse',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XvOgqGxX39f',
                name: '(SURVIVORS) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho Survivors of Abuse',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ZO2Zg7kaYyD',
                allowFuturePeriod: true,
                name: '(SURVIVORS) Projected date for completion',
                translatedName: 'Letsatsi la SURVIVORS le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Ccp4Odlh3BE',
                name: 'COUNSEL',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kGoKVtkQxvk',
                name: '(COUNSEL) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho COUNSEL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yoI0bu18mPo',
                name: '(COUNSEL) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho COUNSEL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Io9nnYXCvWR',
                allowFuturePeriod: true,
                name: '(COUNSEL) Projected date for completion',
                translatedName: 'Letsatsi la COUNSEL le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GO3Ojp1UEX7',
                name: 'FCARE',
                translatedName: 'Tšebeletso a FCARE',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kRwTftt9Nl0',
                name: '(FCARE) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho FCARE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'gi7tMxuE2nG',
                name: '(FCARE) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho FCARE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Trhl3lfCSA6',
                allowFuturePeriod: true,
                name: '(FCARE) Projected date for completion',
                translatedName: 'Letsatsi la FCARE le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'exHDkX1gPiC',
                name: 'SHELTER',
                translatedName: 'Tšebeletso a SHELTER',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vODRi6sq3Pn',
                name: '(SHELTER) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SHELTER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'aVfUmmotSaB',
                name: '(SHELTER) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SHELTER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'MDMmtTJTIyh',
                allowFuturePeriod: true,
                name: '(SHELTER) Projected date for completion',
                translatedName: 'Letsatsi la SHELTER le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yf6KmY3Rm5I',
                name: 'ABUSE',
                translatedName: 'Tšebeletso a ABUSE',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'oth3dRYox12',
                name: '(ABUSE) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho ABUSE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'RsCebbDkMx9',
                name: '(ABUSE) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho ABUSE',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'YtwjCoHKA9G',
                allowFuturePeriod: true,
                name: '(ABUSE) Projected date for completion',
                translatedName: 'Letsatsi la ABUSE le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WdZ3PnW5yV6',
                name: 'LEGALPROT',
                translatedName: 'Tšebeletso a LEGALPROT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dJR6GJyHCTr',
                name: '(LEGALPROT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho LEGALPROT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cu1UkUUTbME',
                name: '(LEGALPROT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho LEGALPROT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OIw6D3I6BmY',
                allowFuturePeriod: true,
                name: '(LEGALPROT) Projected date for completion',
                translatedName: 'Letsatsi la LEGALPROT le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'hS7aONLz2cq',
                name: 'BIRTHCERT',
                translatedName: 'Tšebeletso a BIRTHCERT',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'LDH3TLjHUYK',
                name: '(BIRTHCERT) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Pd5CyDu2Z54',
                name: '(BIRTHCERT) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SvkvfRNqyh2',
                allowFuturePeriod: true,
                name: '(BIRTHCERT) Projected date for completion',
                translatedName: 'Letsatsi la BIRTHCERT le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373))
          ]),
      FormSection(
          id: 'Schooled',
          name: 'DOMAIN SCHOOLED',
          translatedName: 'TSA SEKOLO',
          color: const Color(0xFF9B2BAE),
          borderColor: const Color(0xFF9B2BAE),
          inputFields: [
            InputField(
                id: 'QjlTTO5KAIf',
                name: 'Identified need/Gap',
                translatedName: 'Litlhoko kapa likhahello tse hloauoeng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Cb8qzfdrg7d',
                name: 'Aflatoun/teen',
                translatedName: 'Tšebeletso a Aflatoun/teen',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JiqD0sYv7pH',
                name: '(Aflatoun/teen) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'vqmvjogGeX5',
                name: '(Aflatoun/teen) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HeoYwEJukC8',
                allowFuturePeriod: true,
                name: '(Aflatoun/teen) Projected date for completion',
                translatedName: 'Letsatsi la Aflatoun/teen le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'TQSMaZgfZPO',
                name: 'PTS4G',
                translatedName: 'Tšebeletso a PTS4G',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'do1fAllY7Jv',
                name: '(PTS4G) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho PTS4G',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'y5v9t8Skiyi',
                name: '(PTS4G) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho PTS4G',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'mvuyd2jt4Jz',
                allowFuturePeriod: true,
                name: '(PTS4G) Projected date for completion',
                translatedName: 'Letsatsi la PTS4G le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'SN2kJN3jAG9',
                name: 'PTS4NG',
                translatedName: 'Tšebeletso a PTS4NG',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'k9R0AUmBqHS',
                name: '(PTS4NG) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho PTS4NG',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'k2eUheeYmfk',
                name: '(PTS4NG) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho PTS4NG',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'bIMwh3ONDGq',
                allowFuturePeriod: true,
                name: '(PTS4NG) Projected date for completion',
                translatedName: 'Letsatsi la PTS4NG le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'X47zxNAqMv0',
                name: 'HWCLUB',
                translatedName: 'Tšebeletso ea HWCLUB',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'kfcqLf2d2dc',
                name: '(HWCLUB) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho HWCLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ewpLauNhb8N',
                name: '(HWCLUB) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho HWCLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rPhOdwWvfOA',
                allowFuturePeriod: true,
                name: '(HWCLUB) Projected date for completion',
                translatedName: 'Letsatsi la HWCLUB le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'qraZh4n14S4',
                name: 'BURSARY',
                translatedName: 'Tšebeletso ea BURSARY',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dSS3xEVkH26',
                name: '(BURSARY) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho BURSARY',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'JXx3FiIQe08',
                name: '(BURSARY) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho BURSARY',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ZwGE57BjVdJ',
                allowFuturePeriod: true,
                name: '(BURSARY) Projected date for completion',
                translatedName: 'Letsatsi la BURSARY le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'TdReJf2LTXA',
                name: 'SFEES',
                translatedName: 'Tšebeletso a SFEES',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EonyCjxIh5l',
                name: '(SFEES) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SFEES',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'meR35m2WVNZ',
                name: '(SFEES) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SFEES',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'YIFHsUgTAlI',
                allowFuturePeriod: true,
                name: '(SFEES) Projected date for completion',
                translatedName: 'Letsatsi la SFEES le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'q2N7p3UbvSF',
                name: 'SMATERIAL',
                translatedName: 'Tšebeletso a SMATERIAL',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XFY4FxA7ymC',
                name: '(SMATERIAL) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho SMATERIAL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'rjKp0pEFJ2L',
                name: '(SMATERIAL) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho SMATERIAL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Gw1wRcsPemn',
                allowFuturePeriod: true,
                name: '(SMATERIAL) Projected date for completion',
                translatedName: 'Letsatsi la SMATERIAL le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'NcMANzhhphO',
                name: 'REENROL',
                translatedName: 'Tšebeletso a REENROL',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'fT9sHAd6Gvw',
                name: '(REENROL) Name of responsible internal person',
                translatedName: 'Motho ea ikarabellang ka hare ho REENROL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'lO7yfY3mBYB',
                name: '(REENROL) Name of responsible external Person',
                translatedName: 'Motho ea ikarabellang ka ntle ho REENROL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GhPb5Acr00X',
                allowFuturePeriod: true,
                name: '(REENROL) Projected date for completion',
                translatedName: 'Letsatsi la REENROL le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          name: 'Other Activities',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
                id: 'QjlTTO5KAIf',
                name: 'Identified need/Gap',
                translatedName: 'Litlhoko kapa likhahello tse hloauoeng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ksc7ov3MihX',
                name: 'OTHER ACTIVITIES',
                translatedName: 'Mesebetsi e meng',
                valueType: 'TRUE_ONLY',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Mq7g4k4lk44',
                name: '(Other activities) Name of responsible internal person',
                translatedName:
                    'Motho ea ikarabellang ka hare ho Mesebetsi e meng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XSTUvAjvijB',
                name: '(Other activities) Name of responsible external Person',
                translatedName:
                    'Motho ea ikarabellang ka ntle ho Mesebetsi e meng',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'LGsvIyYkrP8',
                allowFuturePeriod: true,
                name: '(Other activities) Projected date for completion',
                translatedName: 'Letsatsi la Mesebetsi e meng le tla phetheloa',
                valueType: 'DATE',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          ])
    ];
  }
}
