import 'package:flutter/material.dart';
import 'package:kb_mobile_app/models/form_section.dart';
import 'package:kb_mobile_app/models/input_field.dart';

class OvcServicesChildServiceProvision {
  static List<FormSection> getFormSections({
    required String firstDate,
  }) {
    return [
      FormSection(
          id: 'Health',
          name: 'DOMAIN HEALTH',
          translatedName: 'BOPHELO BO BOTLE',
          color: const Color(0xFF4D9E49),
          borderColor: const Color(0xFF4D9E49),
          inputFields: [
            InputField(
              id: 'y8ToqnbVz1o',
              name: 'HIVS&D Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVSCREEN',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'GyG2HcLsVka',
                name: 'HIVS&D Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVS&D',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'uU4TvD2O1uL',
              name: 'HIVS&D session number',
              translatedName: 'Thupelo ea HIVS&D',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'dwhnvU5m667',
                name: 'HIVS&D Comment',
                translatedName: 'Tlhaloso ea HIVS&D',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'mRoO7kgpgVg',
              name: 'CCFLS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'CIRXgKGOmSI',
                name: 'CCFLS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa CCFLS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'wfiqfXHUBde',
              name: 'CCFLS session number',
              translatedName: 'Thupelo ea CCFLS',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'YSsfKXdIRLG',
                name: 'CCFLS Comment',
                translatedName: 'Tlhaloso ea CCFLS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'GNQ3gDA2CTI',
              name: 'CHILD STIMULATION  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'oTSVSO3iHTk',
                name: 'CHILD STIMULATION  Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa CHILD STIMULATION ',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'PYMmQdzlPLJ',
              name: 'CHILD STIMULATION  session number',
              translatedName: 'Thupelo ea CHILD STIMULATION ',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'aDOvfQ1wdIX',
                name: 'CHILD STIMULATION  Comment',
                translatedName: 'Tlhaloso ea CHILD STIMULATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'gSp9bgPW52L',
              name: 'TB SCREENING  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'fVpcWBp0Ngp',
                name: 'TB SCREENING Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa TB SCREENING ',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'pSkl6ibruvU',
                name: 'TB SCREENING  Comment',
                translatedName: 'Tlhaloso ea TB SCREENING ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'tnspdPfpuXm',
              name: 'FOOD PREV  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'V1HnY5m2Pmv',
                name: 'FOOD PREV Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD PREV',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'YRUnLuPerwn',
              name: 'FOOD PREV  session number',
              translatedName: 'Thupelo ea FOOD PREV ',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'eXh6Gag1uwp',
                name: 'FOOD PREV  Comment',
                translatedName: 'Tlhaloso ea FOOD PREV ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'zK7kMYpgPQn',
              name: 'FOOD PREP  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'GtejBpkVvtD',
                name: 'FOOD PREP Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD PREP',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'F6z3SQxLskG',
              name: 'FOOD PREP session number',
              translatedName: 'Thupelo ea FOOD PREP ',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'g2X9vUL2d9m',
                name: 'FOOD PREP Comment',
                translatedName: 'Tlhaloso ea FOOD PREP ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'FRWCmEerPic',
              name: 'TIPPY TAP  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              isReadOnly: true,
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'lQYnoeqfKpe',
                name: 'TIPPY TAP Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa TIPPY TAP',
                isReadOnly: true,
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'IiIVDSKX8yk',
                name: 'TIPPY TAP Comment',
                translatedName: 'Tlhaloso ea TIPPY TAP',
                isReadOnly: true,
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'qL9c5r7c6kK',
              name: 'SOACKAGE PIT  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              isReadOnly: true,
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'pUphS6E1Gu5',
                name: 'SOACKAGE PIT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SOACKAGE PIT ',
                isReadOnly: true,
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'k5RGRpWRbbs',
              name: 'SOACKAGE PIT  session number',
              translatedName: 'Thupelo ea SOACKAGE PIT ',
              isReadOnly: true,
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'SODPuEmHEGV',
                name: 'SOACKAGE PIT Comment',
                translatedName: 'Tlhaloso ea SOACKAGE PIT',
                isReadOnly: true,
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'gV77yUM8NK8',
              name: 'WASH MESSAGING  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea CCFLS',
              isReadOnly: true,
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'aqJBZDBzh4m',
                name: 'WASH MESSAGING Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa WASH MESSAGING ',
                isReadOnly: true,
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'EtENRPlSnO0',
              name: 'WASH MESSAGING  session number',
              translatedName: 'Thupelo ea WASH MESSAGING',
              isReadOnly: true,
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'JFlnkaXlXm5',
                name: 'WASH MESSAGING Comment',
                translatedName: 'Tlhaloso ea WASH MESSAGING',
                isReadOnly: true,
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'otd2tndsE4Z',
              name: 'HIV ADHERANCE SUPPORT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVSCREEN',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'ruZFn94Hcyw',
                name: 'HIV ADHERANCE SUPPORT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa HIV ADHERANCE SUPPORT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'dwhnvU5m667',
                name: 'HIV ADHERANCE SUPPORT Comment',
                translatedName: 'Tlhaloso ea HIV ADHERANCE SUPPORT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'JnqldNamliR',
              name: 'HTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HTS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'CNnzifTDF5a',
                name: 'HTS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HTS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'sxlVgySosg3',
                name: 'HTS Comment',
                translatedName: 'Tlhaloso ea HTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'YFgrURiwirq',
              name: 'HIVTREAT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HIVTREAT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'LtiZFxXw0Wc',
                name: 'HIVTREAT Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HIVTREAT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'i9icxSZ8HCf',
                name: 'HIVTREAT Comment',
                translatedName: 'Tlhaloso ea HIVTREAT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'ESIjwQ9S6Ic',
              name: 'PRG&L Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea PRG&L',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EYv3aMwJOUN',
                name: 'PRG&L Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa PRG&L',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'GISFLEttRtU',
                name: 'PRG&L Comment',
                translatedName: 'Tlhaloso ea PRG&L',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'r8wPQAog7PJ',
              name: 'SAIDS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SAIDS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'EgbO5h9cs5D',
                name: 'SAIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SAIDS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'itTgPQ0OrMU',
                name: 'SAIDS Comment',
                translatedName: 'Tlhaloso ea SAIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'UKczyQWCB0L',
              name: 'IMMUNIZATION Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea IMMUNIZATION',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'jsEr16lnber',
                name: 'IMMUNIZATION Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa IMMUNIZATION',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'LUyWbpKKNgW',
              name: 'HIMMUNIZATION  session number',
              translatedName: 'Thupelo ea IMMUNIZATION',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'wZLjymsKsuj',
                name: 'IMMUNIZATION Comment',
                translatedName: 'Tlhaloso ea IMMUNIZATION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'KkqMjxjAR7g',
              name: 'MALNUTRITION Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea IMMUNIZATION',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'gYAZrh9o1DB',
                name: 'MALNUTRITION Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa MALNUTRITION',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'uqYcjiXv41F',
              name: 'MALNUTRITION  session number',
              translatedName: 'Thupelo ea MALNUTRITION',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'Jxlug5I3kdu',
                name: 'MALNUTRITION Comment',
                translatedName: 'Tlhaloso ea MALNUTRITION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'mY7GqOTKtsQ',
              name: 'TB REFFER Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TB REFFER',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'h6obb1v1stw',
                name: 'TB REFFER Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa TB REFFER',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'ydZH3TOpsXS',
              name: 'TB REFFER  session number',
              translatedName: 'Thupelo ea TB REFFER',
              valueType: 'TEXT',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'kBivIQr6mrW',
                name: 'TB REFFER Comment',
                translatedName: 'Tlhaloso ea TB REFFER',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'DoU7AeHDsUs',
              name: 'FOOD SUPPLIMENTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea TB REFFER',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'wjD9ZJmft7n',
                name: 'FOOD SUPPLIMENTS Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FOOD SUPPLIMENTS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Op6ws25fWWQ',
                name: 'FOOD SUPPLIMENTS Comment',
                translatedName: 'Tlhaloso ea FOOD SUPPLIMENTS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'eqhzeRBMftZ',
              name: 'HEALTH Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea HEALTH',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF4D9E49),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'F8x8QAoFQBO',
                name: 'HEALTH Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa HEALTH',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'AStxMCkJhi5',
                name: 'HEALTH Comment',
                translatedName: 'Tlhaloso ea HEALTH',
                valueType: 'TEXT',
                inputColor: const Color(0xFF4D9E49),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Stable',
          name: 'DOMAIN STABLE',
          translatedName: 'BOTSITSO',
          color: const Color(0xFF0000FF),
          borderColor: const Color(0xFF0000FF),
          inputFields: [
            InputField(
              id: 'xTO562B5g53',
              name: 'SILC Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SILC',
              isReadOnly: true,
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'uOMr56xoKDh',
                name: 'SILC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SILC',
                isReadOnly: true,
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'hMdC0CMKSGn',
                name: 'SILC Comment',
                translatedName: 'Tlhaloso ea SILC',
                isReadOnly: true,
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'AnnOS2m6LZK',
              name: 'Savings Group Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SGROUP',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'UHWzhDsQdoB',
                name: 'Savings Group Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa Savings Group',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WA8MAXBxaD1',
                name: 'Savings Group session number',
                translatedName: 'Thupelo ea Saving Group',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'xECpX8Vt1rT',
                name: 'Savings Group Comment',
                translatedName: 'Tlhaloso ea Savings Group',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'lpTVK3t1Ahk',
              name: 'FINANCIAL EDUCATION  Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SGROUP',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'j1yzHzO0w6w',
                name: 'FINANCIAL EDUCATION  Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa FINANCIAL EDUCATION ',
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'KvHf0rBfa1L',
                name: 'FINANCIAL EDUCATION  session number',
                translatedName: 'Thupelo ea FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'HGpA4kx5jLQ',
                name: 'FINANCIAL EDUCATION  Comment',
                translatedName: 'Tlhaloso ea FINANCIAL EDUCATION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'lEkrLOFmLrH',
              name: 'K/TPLOTS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea K/TPLOTS',
              isReadOnly: true,
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0000FF),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'F8ALMOcc6C1',
                name: 'K/TPLOTS  Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa K/TPLOTS',
                isReadOnly: true,
                valueType: 'DATE',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'ereN7hP7yuT',
                name: 'K/TPLOTS  session number',
                translatedName: 'Thupelo ea K/TPLOTS',
                isReadOnly: true,
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'p77CBdxxtHI',
                name: 'K/TPLOTS  Comment',
                translatedName: 'Tlhaloso ea K/TPLOTS',
                isReadOnly: true,
                valueType: 'TEXT',
                inputColor: const Color(0xFF0000FF),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Safe',
          name: 'DOMAIN SAFE',
          translatedName: 'TSIRELETSO',
          color: const Color(0xFF0F9587),
          borderColor: const Color(0xFF0F9587),
          inputFields: [
            InputField(
              id: 'RNKOtUtLT4c',
              name: 'SLION Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SLION',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'sa79KxTFGFA',
                name: 'SLION Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SLION',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'FAqGmEGN1sa',
                name: 'SLION  session number',
                translatedName: 'Thupelo ea SLION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EB3JPVqMdb4',
                name: 'SLION Comment',
                translatedName: 'Tlhaloso ea SLION',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'GImA3HB9YK5',
              name: 'RTEEN Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea RTEEN',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'fFuabYbLUjz',
                name: 'RTEEN Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa RTEEN',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'QBNhlIan0LR',
                name: 'RTEEN/Parenting session number',
                translatedName: 'Thupelo ea RTEEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'IFggJCXLYPD',
                name: 'RTEEN Comment',
                translatedName: 'Tlhaloso ea RTEEN',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'Fj2RbXsb8Yj',
              name: 'RKIDS Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea RKIDS',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'f90c5olxs5Z',
                name: 'RKIDS Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa RKIDS',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'xbMtMJ9Uo5j',
                name: 'RKIDS session number',
                translatedName: 'Thupelo ea RKIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'EPwDypaz61A',
                name: 'RKIDS Comment',
                translatedName: 'Tlhaloso ea RKIDS',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'gwwUOs6yt6C',
              name: 'P&FC Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea P&FC',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'w2HlBCfHbZR',
                name: 'P&FC Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa P&FC',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'n30r7v0ti1s',
                name: 'P&FC session number',
                translatedName: 'Thupelo ea P&FC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'aG42nUguLLW',
                name: 'P&FC Comment',
                translatedName: 'Tlhaloso ea P&FC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'rMtSykWZ4HB',
              name: 'VAC MESSAGING Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'qwnfgBG2web',
                name: 'VAC MESSAGING Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa VAC MESSAGING',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'YPImSLRMLWH',
                name: 'VAC MESSAGING session number',
                // translatedName: 'Boemo ba Phano ea Litšebeletso ea VAC',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'OMhFxj6SYhM',
                name: 'VAC MESSAGING Comment',
                translatedName: 'Tlhaloso ea VAC MESSAGING',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'QDFZ03HbjGj',
              name: 'VAC Legal Messaging Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea VAC Legal Messaging',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'Dw1xLXILErU',
                name: 'VAC Legal Messaging Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa VAC Legal Messaging',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'P4PMMDgWCSA',
                name: 'VAC Legal Messaging session number',
                translatedName: 'Thupelo ea VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'KWk8waoLO7N',
                name: 'VAC Legal Messaging Comment',
                translatedName: 'Tlhaloso ea VAC Legal Messaging',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'ysDSdiL7wNx',
              name: 'COUNSEL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea COUNSEL',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'pBVmFpsSGN7',
                name: 'COUNSEL Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa COUNSEL',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'LkQxvdt6YCw',
                name: 'COUNSEL session number',
                translatedName: 'Thupelo ea COUNSEL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'XUoqvbk0uVH',
                name: 'COUNSEL Comment',
                translatedName: 'Tlhaloso ea COUNSEL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'aGChpBlIzcd',
              name: 'BIRTHCERT Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea BIRTHCERT',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'AXLxNo9pz8c',
                name: 'BIRTHCERT Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa BIRTHCERT',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'RTEBrgDTe02',
                name: 'BIRTHCERT session number',
                translatedName: 'Thupelo ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cb773khL7XB',
                name: 'BIRTHCERT Comment',
                translatedName: 'Tlhaloso ea BIRTHCERT',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'gfKsz88uxtg',
              name: 'LEGAL PROTECTION  Service provided',
              // translatedName:
              //     'Boemo ba Phano ea Litšebeletso ea LEGAL PROTECTION ',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF0F9587),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'P06od0qmlSR',
                name: 'LEGAL PROTECTION  Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa LEGAL PROTECTION ',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'NwtohlveKHW',
                name: 'LEGAL PROTECTION  session number',
                translatedName: 'Thupelo ea LEGAL PROTECTION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'iz4CvIFovsF',
                name: 'LEGAL PROTECTION  Comment',
                translatedName: 'Tlhaloso ea LEGAL PROTECTION ',
                valueType: 'TEXT',
                inputColor: const Color(0xFF0F9587),
                labelColor: const Color(0xFF737373)),
          ]),
      FormSection(
          id: 'Schooled',
          name: 'DOMAIN SCHOOLED',
          translatedName: 'TSA SEKOLO',
          color: const Color(0xFF9B2BAE),
          borderColor: const Color(0xFF9B2BAE),
          inputFields: [
            InputField(
              id: 'LcIB5EL3IjT',
              name: 'Aflatoun/teen Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea Aflatoun/teen',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF9B2BAE),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'zYrrrFd48S5',
                name: 'Aflatoun/teen Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa Aflatoun/teen',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'g0WhpZC7Rhe',
                name: 'Aflatoun/teen session number',
                translatedName: 'Thupelo ea Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'WVsVwfErZ7V',
                name: 'Aflatoun/teen Comment',
                translatedName: 'Tlhaloso ea Aflatoun/teen',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'hg2bpp1HqwU',
              name: 'HOMEWORK CLUB Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea Aflatoun/teen',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF9B2BAE),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'wB2jXLTYtDb',
                name: 'HOMEWORK CLUBService Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa HOMEWORK CLUB',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'cuLeuQsq7ZG',
                name: 'HOMEWORK CLUB session number',
                translatedName: 'Thupelo ea HOMEWORK CLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'Riyr0nniCVo',
                name: 'HOMEWORK CLUB Comment',
                translatedName: 'Tlhaloso ea HOMEWORK CLUB',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'fvgPnlOD7e9',
              name: 'BURSARY Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea BURSARY',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF9B2BAE),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'JFetYCY5tza',
                name: 'BURSARY Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa BURSARY',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'yuwtSD8EyoY',
                name: 'BURSARY Comment',
                translatedName: 'Tlhaloso ea BURSARY',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'WQlWXUmYjI2',
              name: 'SMATERIAL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SMATERIAL',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF9B2BAE),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'gAMv1jxS0rh',
                name: 'SMATERIAL Service Provision Date',
                translatedName:
                    'Letsatsi la Kabo ea Litšebeletso tsa SMATERIAL',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'CxREUNzKxHB',
                name: 'SMATERIAL Comment',
                translatedName: 'Tlhaloso ea SMATERIAL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'Zc0M1jsbfyA',
              name: 'REENROL Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea REENROL',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF9B2BAE),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'mLjRp8wJ8aW',
                name: 'REENROL Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa REENROL',
                valueType: 'DATE',
                firstDate: firstDate,
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'QCbFgssCzeF',
                name: 'REENROL Comment',
                translatedName: 'Tlhaloso ea REENROL',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
              id: 'MeMaUvt3O8j',
              name: 'SFEES Service provided',
              // translatedName: 'Boemo ba Phano ea Litšebeletso ea SFEES',
              valueType: 'TRUE_ONLY',
              inputColor: const Color(0xFF9B2BAE),
              labelColor: const Color(0xFF737373),
            ),
            InputField(
                id: 'KZIjTeMl7sj',
                name: 'SFEES Service Provision Date',
                translatedName: 'Letsatsi la Kabo ea Litšebeletso tsa SFEES',
                valueType: 'DATE',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
            InputField(
                id: 'KppYygPZ8BL',
                name: 'SFEES Comment',
                translatedName: 'Tlhaloso ea SFEES',
                valueType: 'TEXT',
                inputColor: const Color(0xFF9B2BAE),
                labelColor: const Color(0xFF737373)),
          ]),
    ];
  }
}
