class AgywDreamsServiceFormSessions {
  static final Map<String, List> sessionMapping = {
    'CondomEducationProvision': ['1', '2', '4', '6', '7', '8', '9', '10'],
    'Go Girls': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14',
      '15'
    ],
    'AFLATEEN/TOUN': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ],
    'ViolencePreventionEducation': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ],
    'FinancialLiteracyEducation': ['1', '2', '3', '4'],
    'SAVING GROUP': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ],
    'SILC': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
    ],
    'LBSE': ['1', '2', '3', '4', '5', '6'],
    'PARENTING': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
      '13',
      '14'
    ],
    'HIV Prevention Education': ['1', '2', '3', '4'],
  };
}
