class ProgramStagesConstants {
  static final Map programStages = {
    "gkNKXUxpyv9": "Identified Needs/Gaps",
    "nyiY3suHUfb": "9-14 OGAC Module",
    "uEwup8PaVBd": "Adult and Child Well being Assessment",
    "uctHRP6BBXP": "AGYW/Dreams None Participation Form",
    "wA5y7RU83lF": "ANC",
    "Gk494qKQP8B": "ART Re-fill",
    "ulaeRwJNuk7": "BIO DATA: Index contacts",
    "f46dsAjLpgN": "BIO DATA: Information about elicited Sexual Partners",
    "Mw4jw8RCSdy": "BIO Data: Information about Index Positive client",
    "FMjrtxV9w82": "Case Closure",
    "IjQP2OHQGrL": "Case Closure Checklist",
    "PX7VxEi76K9": "Case Plan",
    "ZHjrdThi7Bz": "Case Plan",
    "gtERzyY2f49": "Case Plan Achievement Readiness Assessment",
    "vjF07cZNST3": "Case Plan: Gap",
    "dlR2wsNprZI": "Case Plan: Graduation",
    "KGMk9faQkk6": "Case Transfer",
    "sFpMZtePzOy": "Case Transfer",
    "EvEQIT21a9S": "CLO Outgoing Referrals",
    "JUkByM64g6e": "CLO Outgoing Referrals",
    "aNigUqZ9Woh": "CLO Outgoing Referrals",
    "WvWG41jo22m": "CLO Received Referrals",
    "nu9fJ7p0w0R": "CLO Received Referrals",
    "wQ41r6PSid7": "CLO Received Referrals",
    "NXsIkG9Q1BA": "Condoms",
    "AkbbzsszCOJ": "Consent & None Participation to Programme",
    "A7Tl3vML6as": "Contraceptives",
    "GJMtfOWadC0": "Exit",
    "IHc7aMmyTvq": "Exit ",
    "iAOodcxVY6I": "Go Girls",
    "PGFt6IwdZLM": "HIV Messaging",
    "j1NBiz7DC41": "HIV Register",
    "Pb1Gb4Aky92": "HIV Risk Assessment",
    "QNdBI9U7rnV": "HTS",
    "kq6qeEgbDVY": "HTS Register",
    "vAMc8n0YB6m": "HTS Short Form",
    "HTJiRLo6M6X": "LBSE",
    "JQ74V6yd9On": "On going Monitoring",
    "v9Vrc5exzam": "On going monitoring",
    "CEyIqiOZOwx": "PEP",
    "yK0ENCuwPqh": "Post GBV",
    "Yn6AJ0CAxb2": "PrEP Follow Up visits",
    "nVCqxOg0nMQ": "PrEP Follow Up Visits",
    "mMjGlK1W0Xo": "PrEP Intake",
    "Qw8c20q5V0w": "PrEP Intake Short Form",
    "MkyTrLeBG8I": "Referral",
    "pnEgjBdFctR": "Referral",
    "wPk6BYPm3Wo": "Referral",
    "HxUr3gvf5FA": "Referral Follow Up",
    "a7b8GrXEaQy": "Referral Follow Up",
    "s827JhUFGYQ": "Referral Follow Up",
    "dVdlJNtNLIQ": "School Performance-Progression Tracking",
    "CHFwighOquA": "Service Follow Up",
    "vcaHzmUuYzU": "Service Follow Up",
    "bDJq2JWVTbC": "Service Form",
    "K61XAaNlbbU": "SRH Client Intake",
    "dSOwDM6JGWe": "SRH Register",
    "i9sW7OP4xZs": "Stepping Stones",
    "bcwUphHTXrH": "TB Screening",
    "GPg1J1xIHT6": "Tb screening tool",
    "RJTRRO0wg8H": "Well-being Assessment"
  };
}
